# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.40
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_CppBlockUtils', [dirname(__file__)])
        except ImportError:
            import _CppBlockUtils
            return _CppBlockUtils
        if fp is not None:
            try:
                _mod = imp.load_module('_CppBlockUtils', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _CppBlockUtils = swig_import_helper()
    del swig_import_helper
else:
    import _CppBlockUtils
del version_info
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

class SwigPyIterator:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _CppBlockUtils.delete_SwigPyIterator
    __del__ = lambda self : None;
    def value(self): return _CppBlockUtils.SwigPyIterator_value(self)
    def incr(self, n = 1): return _CppBlockUtils.SwigPyIterator_incr(self, n)
    def decr(self, n = 1): return _CppBlockUtils.SwigPyIterator_decr(self, n)
    def distance(self, *args): return _CppBlockUtils.SwigPyIterator_distance(self, *args)
    def equal(self, *args): return _CppBlockUtils.SwigPyIterator_equal(self, *args)
    def copy(self): return _CppBlockUtils.SwigPyIterator_copy(self)
    def next(self): return _CppBlockUtils.SwigPyIterator_next(self)
    def __next__(self): return _CppBlockUtils.SwigPyIterator___next__(self)
    def previous(self): return _CppBlockUtils.SwigPyIterator_previous(self)
    def advance(self, *args): return _CppBlockUtils.SwigPyIterator_advance(self, *args)
    def __eq__(self, *args): return _CppBlockUtils.SwigPyIterator___eq__(self, *args)
    def __ne__(self, *args): return _CppBlockUtils.SwigPyIterator___ne__(self, *args)
    def __iadd__(self, *args): return _CppBlockUtils.SwigPyIterator___iadd__(self, *args)
    def __isub__(self, *args): return _CppBlockUtils.SwigPyIterator___isub__(self, *args)
    def __add__(self, *args): return _CppBlockUtils.SwigPyIterator___add__(self, *args)
    def __sub__(self, *args): return _CppBlockUtils.SwigPyIterator___sub__(self, *args)
    def __iter__(self): return self
SwigPyIterator_swigregister = _CppBlockUtils.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class vector_int:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vector_int, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vector_int, name)
    __repr__ = _swig_repr
    def iterator(self): return _CppBlockUtils.vector_int_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _CppBlockUtils.vector_int___nonzero__(self)
    def __bool__(self): return _CppBlockUtils.vector_int___bool__(self)
    def __len__(self): return _CppBlockUtils.vector_int___len__(self)
    def pop(self): return _CppBlockUtils.vector_int_pop(self)
    def __getslice__(self, *args): return _CppBlockUtils.vector_int___getslice__(self, *args)
    def __setslice__(self, *args): return _CppBlockUtils.vector_int___setslice__(self, *args)
    def __delslice__(self, *args): return _CppBlockUtils.vector_int___delslice__(self, *args)
    def __delitem__(self, *args): return _CppBlockUtils.vector_int___delitem__(self, *args)
    def __getitem__(self, *args): return _CppBlockUtils.vector_int___getitem__(self, *args)
    def __setitem__(self, *args): return _CppBlockUtils.vector_int___setitem__(self, *args)
    def append(self, *args): return _CppBlockUtils.vector_int_append(self, *args)
    def empty(self): return _CppBlockUtils.vector_int_empty(self)
    def size(self): return _CppBlockUtils.vector_int_size(self)
    def clear(self): return _CppBlockUtils.vector_int_clear(self)
    def swap(self, *args): return _CppBlockUtils.vector_int_swap(self, *args)
    def get_allocator(self): return _CppBlockUtils.vector_int_get_allocator(self)
    def begin(self): return _CppBlockUtils.vector_int_begin(self)
    def end(self): return _CppBlockUtils.vector_int_end(self)
    def rbegin(self): return _CppBlockUtils.vector_int_rbegin(self)
    def rend(self): return _CppBlockUtils.vector_int_rend(self)
    def pop_back(self): return _CppBlockUtils.vector_int_pop_back(self)
    def erase(self, *args): return _CppBlockUtils.vector_int_erase(self, *args)
    def __init__(self, *args): 
        this = _CppBlockUtils.new_vector_int(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _CppBlockUtils.vector_int_push_back(self, *args)
    def front(self): return _CppBlockUtils.vector_int_front(self)
    def back(self): return _CppBlockUtils.vector_int_back(self)
    def assign(self, *args): return _CppBlockUtils.vector_int_assign(self, *args)
    def resize(self, *args): return _CppBlockUtils.vector_int_resize(self, *args)
    def insert(self, *args): return _CppBlockUtils.vector_int_insert(self, *args)
    def reserve(self, *args): return _CppBlockUtils.vector_int_reserve(self, *args)
    def capacity(self): return _CppBlockUtils.vector_int_capacity(self)
    __swig_destroy__ = _CppBlockUtils.delete_vector_int
    __del__ = lambda self : None;
vector_int_swigregister = _CppBlockUtils.vector_int_swigregister
vector_int_swigregister(vector_int)

class vector_float:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vector_float, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vector_float, name)
    __repr__ = _swig_repr
    def iterator(self): return _CppBlockUtils.vector_float_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _CppBlockUtils.vector_float___nonzero__(self)
    def __bool__(self): return _CppBlockUtils.vector_float___bool__(self)
    def __len__(self): return _CppBlockUtils.vector_float___len__(self)
    def pop(self): return _CppBlockUtils.vector_float_pop(self)
    def __getslice__(self, *args): return _CppBlockUtils.vector_float___getslice__(self, *args)
    def __setslice__(self, *args): return _CppBlockUtils.vector_float___setslice__(self, *args)
    def __delslice__(self, *args): return _CppBlockUtils.vector_float___delslice__(self, *args)
    def __delitem__(self, *args): return _CppBlockUtils.vector_float___delitem__(self, *args)
    def __getitem__(self, *args): return _CppBlockUtils.vector_float___getitem__(self, *args)
    def __setitem__(self, *args): return _CppBlockUtils.vector_float___setitem__(self, *args)
    def append(self, *args): return _CppBlockUtils.vector_float_append(self, *args)
    def empty(self): return _CppBlockUtils.vector_float_empty(self)
    def size(self): return _CppBlockUtils.vector_float_size(self)
    def clear(self): return _CppBlockUtils.vector_float_clear(self)
    def swap(self, *args): return _CppBlockUtils.vector_float_swap(self, *args)
    def get_allocator(self): return _CppBlockUtils.vector_float_get_allocator(self)
    def begin(self): return _CppBlockUtils.vector_float_begin(self)
    def end(self): return _CppBlockUtils.vector_float_end(self)
    def rbegin(self): return _CppBlockUtils.vector_float_rbegin(self)
    def rend(self): return _CppBlockUtils.vector_float_rend(self)
    def pop_back(self): return _CppBlockUtils.vector_float_pop_back(self)
    def erase(self, *args): return _CppBlockUtils.vector_float_erase(self, *args)
    def __init__(self, *args): 
        this = _CppBlockUtils.new_vector_float(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _CppBlockUtils.vector_float_push_back(self, *args)
    def front(self): return _CppBlockUtils.vector_float_front(self)
    def back(self): return _CppBlockUtils.vector_float_back(self)
    def assign(self, *args): return _CppBlockUtils.vector_float_assign(self, *args)
    def resize(self, *args): return _CppBlockUtils.vector_float_resize(self, *args)
    def insert(self, *args): return _CppBlockUtils.vector_float_insert(self, *args)
    def reserve(self, *args): return _CppBlockUtils.vector_float_reserve(self, *args)
    def capacity(self): return _CppBlockUtils.vector_float_capacity(self)
    __swig_destroy__ = _CppBlockUtils.delete_vector_float
    __del__ = lambda self : None;
vector_float_swigregister = _CppBlockUtils.vector_float_swigregister
vector_float_swigregister(vector_float)

class vector_BinaryData:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vector_BinaryData, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vector_BinaryData, name)
    __repr__ = _swig_repr
    def iterator(self): return _CppBlockUtils.vector_BinaryData_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _CppBlockUtils.vector_BinaryData___nonzero__(self)
    def __bool__(self): return _CppBlockUtils.vector_BinaryData___bool__(self)
    def __len__(self): return _CppBlockUtils.vector_BinaryData___len__(self)
    def pop(self): return _CppBlockUtils.vector_BinaryData_pop(self)
    def __getslice__(self, *args): return _CppBlockUtils.vector_BinaryData___getslice__(self, *args)
    def __setslice__(self, *args): return _CppBlockUtils.vector_BinaryData___setslice__(self, *args)
    def __delslice__(self, *args): return _CppBlockUtils.vector_BinaryData___delslice__(self, *args)
    def __delitem__(self, *args): return _CppBlockUtils.vector_BinaryData___delitem__(self, *args)
    def __getitem__(self, *args): return _CppBlockUtils.vector_BinaryData___getitem__(self, *args)
    def __setitem__(self, *args): return _CppBlockUtils.vector_BinaryData___setitem__(self, *args)
    def append(self, *args): return _CppBlockUtils.vector_BinaryData_append(self, *args)
    def empty(self): return _CppBlockUtils.vector_BinaryData_empty(self)
    def size(self): return _CppBlockUtils.vector_BinaryData_size(self)
    def clear(self): return _CppBlockUtils.vector_BinaryData_clear(self)
    def swap(self, *args): return _CppBlockUtils.vector_BinaryData_swap(self, *args)
    def get_allocator(self): return _CppBlockUtils.vector_BinaryData_get_allocator(self)
    def begin(self): return _CppBlockUtils.vector_BinaryData_begin(self)
    def end(self): return _CppBlockUtils.vector_BinaryData_end(self)
    def rbegin(self): return _CppBlockUtils.vector_BinaryData_rbegin(self)
    def rend(self): return _CppBlockUtils.vector_BinaryData_rend(self)
    def pop_back(self): return _CppBlockUtils.vector_BinaryData_pop_back(self)
    def erase(self, *args): return _CppBlockUtils.vector_BinaryData_erase(self, *args)
    def __init__(self, *args): 
        this = _CppBlockUtils.new_vector_BinaryData(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _CppBlockUtils.vector_BinaryData_push_back(self, *args)
    def front(self): return _CppBlockUtils.vector_BinaryData_front(self)
    def back(self): return _CppBlockUtils.vector_BinaryData_back(self)
    def assign(self, *args): return _CppBlockUtils.vector_BinaryData_assign(self, *args)
    def resize(self, *args): return _CppBlockUtils.vector_BinaryData_resize(self, *args)
    def insert(self, *args): return _CppBlockUtils.vector_BinaryData_insert(self, *args)
    def reserve(self, *args): return _CppBlockUtils.vector_BinaryData_reserve(self, *args)
    def capacity(self): return _CppBlockUtils.vector_BinaryData_capacity(self)
    __swig_destroy__ = _CppBlockUtils.delete_vector_BinaryData
    __del__ = lambda self : None;
vector_BinaryData_swigregister = _CppBlockUtils.vector_BinaryData_swigregister
vector_BinaryData_swigregister(vector_BinaryData)

class vector_LedgerEntry:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vector_LedgerEntry, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vector_LedgerEntry, name)
    __repr__ = _swig_repr
    def iterator(self): return _CppBlockUtils.vector_LedgerEntry_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _CppBlockUtils.vector_LedgerEntry___nonzero__(self)
    def __bool__(self): return _CppBlockUtils.vector_LedgerEntry___bool__(self)
    def __len__(self): return _CppBlockUtils.vector_LedgerEntry___len__(self)
    def pop(self): return _CppBlockUtils.vector_LedgerEntry_pop(self)
    def __getslice__(self, *args): return _CppBlockUtils.vector_LedgerEntry___getslice__(self, *args)
    def __setslice__(self, *args): return _CppBlockUtils.vector_LedgerEntry___setslice__(self, *args)
    def __delslice__(self, *args): return _CppBlockUtils.vector_LedgerEntry___delslice__(self, *args)
    def __delitem__(self, *args): return _CppBlockUtils.vector_LedgerEntry___delitem__(self, *args)
    def __getitem__(self, *args): return _CppBlockUtils.vector_LedgerEntry___getitem__(self, *args)
    def __setitem__(self, *args): return _CppBlockUtils.vector_LedgerEntry___setitem__(self, *args)
    def append(self, *args): return _CppBlockUtils.vector_LedgerEntry_append(self, *args)
    def empty(self): return _CppBlockUtils.vector_LedgerEntry_empty(self)
    def size(self): return _CppBlockUtils.vector_LedgerEntry_size(self)
    def clear(self): return _CppBlockUtils.vector_LedgerEntry_clear(self)
    def swap(self, *args): return _CppBlockUtils.vector_LedgerEntry_swap(self, *args)
    def get_allocator(self): return _CppBlockUtils.vector_LedgerEntry_get_allocator(self)
    def begin(self): return _CppBlockUtils.vector_LedgerEntry_begin(self)
    def end(self): return _CppBlockUtils.vector_LedgerEntry_end(self)
    def rbegin(self): return _CppBlockUtils.vector_LedgerEntry_rbegin(self)
    def rend(self): return _CppBlockUtils.vector_LedgerEntry_rend(self)
    def pop_back(self): return _CppBlockUtils.vector_LedgerEntry_pop_back(self)
    def erase(self, *args): return _CppBlockUtils.vector_LedgerEntry_erase(self, *args)
    def __init__(self, *args): 
        this = _CppBlockUtils.new_vector_LedgerEntry(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _CppBlockUtils.vector_LedgerEntry_push_back(self, *args)
    def front(self): return _CppBlockUtils.vector_LedgerEntry_front(self)
    def back(self): return _CppBlockUtils.vector_LedgerEntry_back(self)
    def assign(self, *args): return _CppBlockUtils.vector_LedgerEntry_assign(self, *args)
    def resize(self, *args): return _CppBlockUtils.vector_LedgerEntry_resize(self, *args)
    def insert(self, *args): return _CppBlockUtils.vector_LedgerEntry_insert(self, *args)
    def reserve(self, *args): return _CppBlockUtils.vector_LedgerEntry_reserve(self, *args)
    def capacity(self): return _CppBlockUtils.vector_LedgerEntry_capacity(self)
    __swig_destroy__ = _CppBlockUtils.delete_vector_LedgerEntry
    __del__ = lambda self : None;
vector_LedgerEntry_swigregister = _CppBlockUtils.vector_LedgerEntry_swigregister
vector_LedgerEntry_swigregister(vector_LedgerEntry)

class vector_TxRefPtr:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vector_TxRefPtr, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vector_TxRefPtr, name)
    __repr__ = _swig_repr
    def iterator(self): return _CppBlockUtils.vector_TxRefPtr_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _CppBlockUtils.vector_TxRefPtr___nonzero__(self)
    def __bool__(self): return _CppBlockUtils.vector_TxRefPtr___bool__(self)
    def __len__(self): return _CppBlockUtils.vector_TxRefPtr___len__(self)
    def pop(self): return _CppBlockUtils.vector_TxRefPtr_pop(self)
    def __getslice__(self, *args): return _CppBlockUtils.vector_TxRefPtr___getslice__(self, *args)
    def __setslice__(self, *args): return _CppBlockUtils.vector_TxRefPtr___setslice__(self, *args)
    def __delslice__(self, *args): return _CppBlockUtils.vector_TxRefPtr___delslice__(self, *args)
    def __delitem__(self, *args): return _CppBlockUtils.vector_TxRefPtr___delitem__(self, *args)
    def __getitem__(self, *args): return _CppBlockUtils.vector_TxRefPtr___getitem__(self, *args)
    def __setitem__(self, *args): return _CppBlockUtils.vector_TxRefPtr___setitem__(self, *args)
    def append(self, *args): return _CppBlockUtils.vector_TxRefPtr_append(self, *args)
    def empty(self): return _CppBlockUtils.vector_TxRefPtr_empty(self)
    def size(self): return _CppBlockUtils.vector_TxRefPtr_size(self)
    def clear(self): return _CppBlockUtils.vector_TxRefPtr_clear(self)
    def swap(self, *args): return _CppBlockUtils.vector_TxRefPtr_swap(self, *args)
    def get_allocator(self): return _CppBlockUtils.vector_TxRefPtr_get_allocator(self)
    def begin(self): return _CppBlockUtils.vector_TxRefPtr_begin(self)
    def end(self): return _CppBlockUtils.vector_TxRefPtr_end(self)
    def rbegin(self): return _CppBlockUtils.vector_TxRefPtr_rbegin(self)
    def rend(self): return _CppBlockUtils.vector_TxRefPtr_rend(self)
    def pop_back(self): return _CppBlockUtils.vector_TxRefPtr_pop_back(self)
    def erase(self, *args): return _CppBlockUtils.vector_TxRefPtr_erase(self, *args)
    def __init__(self, *args): 
        this = _CppBlockUtils.new_vector_TxRefPtr(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _CppBlockUtils.vector_TxRefPtr_push_back(self, *args)
    def front(self): return _CppBlockUtils.vector_TxRefPtr_front(self)
    def back(self): return _CppBlockUtils.vector_TxRefPtr_back(self)
    def assign(self, *args): return _CppBlockUtils.vector_TxRefPtr_assign(self, *args)
    def resize(self, *args): return _CppBlockUtils.vector_TxRefPtr_resize(self, *args)
    def insert(self, *args): return _CppBlockUtils.vector_TxRefPtr_insert(self, *args)
    def reserve(self, *args): return _CppBlockUtils.vector_TxRefPtr_reserve(self, *args)
    def capacity(self): return _CppBlockUtils.vector_TxRefPtr_capacity(self)
    __swig_destroy__ = _CppBlockUtils.delete_vector_TxRefPtr
    __del__ = lambda self : None;
vector_TxRefPtr_swigregister = _CppBlockUtils.vector_TxRefPtr_swigregister
vector_TxRefPtr_swigregister(vector_TxRefPtr)

class vector_HeaderRefPtr:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vector_HeaderRefPtr, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vector_HeaderRefPtr, name)
    __repr__ = _swig_repr
    def iterator(self): return _CppBlockUtils.vector_HeaderRefPtr_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _CppBlockUtils.vector_HeaderRefPtr___nonzero__(self)
    def __bool__(self): return _CppBlockUtils.vector_HeaderRefPtr___bool__(self)
    def __len__(self): return _CppBlockUtils.vector_HeaderRefPtr___len__(self)
    def pop(self): return _CppBlockUtils.vector_HeaderRefPtr_pop(self)
    def __getslice__(self, *args): return _CppBlockUtils.vector_HeaderRefPtr___getslice__(self, *args)
    def __setslice__(self, *args): return _CppBlockUtils.vector_HeaderRefPtr___setslice__(self, *args)
    def __delslice__(self, *args): return _CppBlockUtils.vector_HeaderRefPtr___delslice__(self, *args)
    def __delitem__(self, *args): return _CppBlockUtils.vector_HeaderRefPtr___delitem__(self, *args)
    def __getitem__(self, *args): return _CppBlockUtils.vector_HeaderRefPtr___getitem__(self, *args)
    def __setitem__(self, *args): return _CppBlockUtils.vector_HeaderRefPtr___setitem__(self, *args)
    def append(self, *args): return _CppBlockUtils.vector_HeaderRefPtr_append(self, *args)
    def empty(self): return _CppBlockUtils.vector_HeaderRefPtr_empty(self)
    def size(self): return _CppBlockUtils.vector_HeaderRefPtr_size(self)
    def clear(self): return _CppBlockUtils.vector_HeaderRefPtr_clear(self)
    def swap(self, *args): return _CppBlockUtils.vector_HeaderRefPtr_swap(self, *args)
    def get_allocator(self): return _CppBlockUtils.vector_HeaderRefPtr_get_allocator(self)
    def begin(self): return _CppBlockUtils.vector_HeaderRefPtr_begin(self)
    def end(self): return _CppBlockUtils.vector_HeaderRefPtr_end(self)
    def rbegin(self): return _CppBlockUtils.vector_HeaderRefPtr_rbegin(self)
    def rend(self): return _CppBlockUtils.vector_HeaderRefPtr_rend(self)
    def pop_back(self): return _CppBlockUtils.vector_HeaderRefPtr_pop_back(self)
    def erase(self, *args): return _CppBlockUtils.vector_HeaderRefPtr_erase(self, *args)
    def __init__(self, *args): 
        this = _CppBlockUtils.new_vector_HeaderRefPtr(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _CppBlockUtils.vector_HeaderRefPtr_push_back(self, *args)
    def front(self): return _CppBlockUtils.vector_HeaderRefPtr_front(self)
    def back(self): return _CppBlockUtils.vector_HeaderRefPtr_back(self)
    def assign(self, *args): return _CppBlockUtils.vector_HeaderRefPtr_assign(self, *args)
    def resize(self, *args): return _CppBlockUtils.vector_HeaderRefPtr_resize(self, *args)
    def insert(self, *args): return _CppBlockUtils.vector_HeaderRefPtr_insert(self, *args)
    def reserve(self, *args): return _CppBlockUtils.vector_HeaderRefPtr_reserve(self, *args)
    def capacity(self): return _CppBlockUtils.vector_HeaderRefPtr_capacity(self)
    __swig_destroy__ = _CppBlockUtils.delete_vector_HeaderRefPtr
    __del__ = lambda self : None;
vector_HeaderRefPtr_swigregister = _CppBlockUtils.vector_HeaderRefPtr_swigregister
vector_HeaderRefPtr_swigregister(vector_HeaderRefPtr)

class vector_UnspentTxOut:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vector_UnspentTxOut, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vector_UnspentTxOut, name)
    __repr__ = _swig_repr
    def iterator(self): return _CppBlockUtils.vector_UnspentTxOut_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _CppBlockUtils.vector_UnspentTxOut___nonzero__(self)
    def __bool__(self): return _CppBlockUtils.vector_UnspentTxOut___bool__(self)
    def __len__(self): return _CppBlockUtils.vector_UnspentTxOut___len__(self)
    def pop(self): return _CppBlockUtils.vector_UnspentTxOut_pop(self)
    def __getslice__(self, *args): return _CppBlockUtils.vector_UnspentTxOut___getslice__(self, *args)
    def __setslice__(self, *args): return _CppBlockUtils.vector_UnspentTxOut___setslice__(self, *args)
    def __delslice__(self, *args): return _CppBlockUtils.vector_UnspentTxOut___delslice__(self, *args)
    def __delitem__(self, *args): return _CppBlockUtils.vector_UnspentTxOut___delitem__(self, *args)
    def __getitem__(self, *args): return _CppBlockUtils.vector_UnspentTxOut___getitem__(self, *args)
    def __setitem__(self, *args): return _CppBlockUtils.vector_UnspentTxOut___setitem__(self, *args)
    def append(self, *args): return _CppBlockUtils.vector_UnspentTxOut_append(self, *args)
    def empty(self): return _CppBlockUtils.vector_UnspentTxOut_empty(self)
    def size(self): return _CppBlockUtils.vector_UnspentTxOut_size(self)
    def clear(self): return _CppBlockUtils.vector_UnspentTxOut_clear(self)
    def swap(self, *args): return _CppBlockUtils.vector_UnspentTxOut_swap(self, *args)
    def get_allocator(self): return _CppBlockUtils.vector_UnspentTxOut_get_allocator(self)
    def begin(self): return _CppBlockUtils.vector_UnspentTxOut_begin(self)
    def end(self): return _CppBlockUtils.vector_UnspentTxOut_end(self)
    def rbegin(self): return _CppBlockUtils.vector_UnspentTxOut_rbegin(self)
    def rend(self): return _CppBlockUtils.vector_UnspentTxOut_rend(self)
    def pop_back(self): return _CppBlockUtils.vector_UnspentTxOut_pop_back(self)
    def erase(self, *args): return _CppBlockUtils.vector_UnspentTxOut_erase(self, *args)
    def __init__(self, *args): 
        this = _CppBlockUtils.new_vector_UnspentTxOut(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _CppBlockUtils.vector_UnspentTxOut_push_back(self, *args)
    def front(self): return _CppBlockUtils.vector_UnspentTxOut_front(self)
    def back(self): return _CppBlockUtils.vector_UnspentTxOut_back(self)
    def assign(self, *args): return _CppBlockUtils.vector_UnspentTxOut_assign(self, *args)
    def resize(self, *args): return _CppBlockUtils.vector_UnspentTxOut_resize(self, *args)
    def insert(self, *args): return _CppBlockUtils.vector_UnspentTxOut_insert(self, *args)
    def reserve(self, *args): return _CppBlockUtils.vector_UnspentTxOut_reserve(self, *args)
    def capacity(self): return _CppBlockUtils.vector_UnspentTxOut_capacity(self)
    __swig_destroy__ = _CppBlockUtils.delete_vector_UnspentTxOut
    __del__ = lambda self : None;
vector_UnspentTxOut_swigregister = _CppBlockUtils.vector_UnspentTxOut_swigregister
vector_UnspentTxOut_swigregister(vector_UnspentTxOut)

class BlockHeader:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, BlockHeader, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, BlockHeader, name)
    __repr__ = _swig_repr
    def getVersion(self): return _CppBlockUtils.BlockHeader_getVersion(self)
    def getPrevHash(self): return _CppBlockUtils.BlockHeader_getPrevHash(self)
    def getMerkleRoot(self): return _CppBlockUtils.BlockHeader_getMerkleRoot(self)
    def getTimestamp(self): return _CppBlockUtils.BlockHeader_getTimestamp(self)
    def getDiffBits(self): return _CppBlockUtils.BlockHeader_getDiffBits(self)
    def getNonce(self): return _CppBlockUtils.BlockHeader_getNonce(self)
    def getThisHash(self): return _CppBlockUtils.BlockHeader_getThisHash(self)
    def getNextHash(self): return _CppBlockUtils.BlockHeader_getNextHash(self)
    def getNumTx(self): return _CppBlockUtils.BlockHeader_getNumTx(self)
    def getBlockHeight(self): return _CppBlockUtils.BlockHeader_getBlockHeight(self)
    def getDifficulty(self): return _CppBlockUtils.BlockHeader_getDifficulty(self)
    def getDifficultySum(self): return _CppBlockUtils.BlockHeader_getDifficultySum(self)
    def isMainBranch(self): return _CppBlockUtils.BlockHeader_isMainBranch(self)
    def isOrphan(self): return _CppBlockUtils.BlockHeader_isOrphan(self)
    def setVersion(self, *args): return _CppBlockUtils.BlockHeader_setVersion(self, *args)
    def setPrevHash(self, *args): return _CppBlockUtils.BlockHeader_setPrevHash(self, *args)
    def setMerkleRoot(self, *args): return _CppBlockUtils.BlockHeader_setMerkleRoot(self, *args)
    def setTimestamp(self, *args): return _CppBlockUtils.BlockHeader_setTimestamp(self, *args)
    def setDiffBits(self, *args): return _CppBlockUtils.BlockHeader_setDiffBits(self, *args)
    def setNonce(self, *args): return _CppBlockUtils.BlockHeader_setNonce(self, *args)
    def setNextHash(self, *args): return _CppBlockUtils.BlockHeader_setNextHash(self, *args)
    def serialize(self, *args): return _CppBlockUtils.BlockHeader_serialize(self, *args)
    def unserialize_1_(self, *args): return _CppBlockUtils.BlockHeader_unserialize_1_(self, *args)
    def unserialize(self, *args): return _CppBlockUtils.BlockHeader_unserialize(self, *args)
    def __init__(self, *args): 
        this = _CppBlockUtils.new_BlockHeader(*args)
        try: self.this.append(this)
        except: self.this = this
    def pprint(self, *args): return _CppBlockUtils.BlockHeader_pprint(self, *args)
    def findNonce(self): return _CppBlockUtils.BlockHeader_findNonce(self)
    __swig_destroy__ = _CppBlockUtils.delete_BlockHeader
    __del__ = lambda self : None;
BlockHeader_swigregister = _CppBlockUtils.BlockHeader_swigregister
BlockHeader_swigregister(BlockHeader)

class OutPoint:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, OutPoint, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, OutPoint, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _CppBlockUtils.new_OutPoint(*args)
        try: self.this.append(this)
        except: self.this = this
    def getTxHash(self): return _CppBlockUtils.OutPoint_getTxHash(self)
    def getTxHashRef(self): return _CppBlockUtils.OutPoint_getTxHashRef(self)
    def getTxOutIndex(self): return _CppBlockUtils.OutPoint_getTxOutIndex(self)
    def setTxHash(self, *args): return _CppBlockUtils.OutPoint_setTxHash(self, *args)
    def setTxOutIndex(self, *args): return _CppBlockUtils.OutPoint_setTxOutIndex(self, *args)
    def __lt__(self, *args): return _CppBlockUtils.OutPoint___lt__(self, *args)
    def __eq__(self, *args): return _CppBlockUtils.OutPoint___eq__(self, *args)
    def serialize(self, *args): return _CppBlockUtils.OutPoint_serialize(self, *args)
    def unserialize(self, *args): return _CppBlockUtils.OutPoint_unserialize(self, *args)
    __swig_destroy__ = _CppBlockUtils.delete_OutPoint
    __del__ = lambda self : None;
OutPoint_swigregister = _CppBlockUtils.OutPoint_swigregister
OutPoint_swigregister(OutPoint)

class TxIn:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, TxIn, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, TxIn, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _CppBlockUtils.new_TxIn(*args)
        try: self.this.append(this)
        except: self.this = this
    def getOutPoint(self): return _CppBlockUtils.TxIn_getOutPoint(self)
    def getBinScript(self): return _CppBlockUtils.TxIn_getBinScript(self)
    def getSequence(self): return _CppBlockUtils.TxIn_getSequence(self)
    def getScriptSize(self): return _CppBlockUtils.TxIn_getScriptSize(self)
    def getSize(self): return _CppBlockUtils.TxIn_getSize(self)
    def setOutPoint(self, *args): return _CppBlockUtils.TxIn_setOutPoint(self, *args)
    def setBinScript(self, *args): return _CppBlockUtils.TxIn_setBinScript(self, *args)
    def setSequence(self, *args): return _CppBlockUtils.TxIn_setSequence(self, *args)
    def setIsMine(self, *args): return _CppBlockUtils.TxIn_setIsMine(self, *args)
    def serialize(self, *args): return _CppBlockUtils.TxIn_serialize(self, *args)
    def unserialize(self, *args): return _CppBlockUtils.TxIn_unserialize(self, *args)
    __swig_destroy__ = _CppBlockUtils.delete_TxIn
    __del__ = lambda self : None;
TxIn_swigregister = _CppBlockUtils.TxIn_swigregister
TxIn_swigregister(TxIn)

class TxOut:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, TxOut, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, TxOut, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _CppBlockUtils.new_TxOut(*args)
        try: self.this.append(this)
        except: self.this = this
    def getValue(self): return _CppBlockUtils.TxOut_getValue(self)
    def getPkScript(self): return _CppBlockUtils.TxOut_getPkScript(self)
    def getScriptSize(self): return _CppBlockUtils.TxOut_getScriptSize(self)
    def isStandard(self): return _CppBlockUtils.TxOut_isStandard(self)
    def getRecipientAddr(self): return _CppBlockUtils.TxOut_getRecipientAddr(self)
    def setValue(self, *args): return _CppBlockUtils.TxOut_setValue(self, *args)
    def setPkScript(self, *args): return _CppBlockUtils.TxOut_setPkScript(self, *args)
    def serialize(self, *args): return _CppBlockUtils.TxOut_serialize(self, *args)
    def unserialize(self, *args): return _CppBlockUtils.TxOut_unserialize(self, *args)
    __swig_destroy__ = _CppBlockUtils.delete_TxOut
    __del__ = lambda self : None;
TxOut_swigregister = _CppBlockUtils.TxOut_swigregister
TxOut_swigregister(TxOut)

class Tx:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Tx, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Tx, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _CppBlockUtils.new_Tx()
        try: self.this.append(this)
        except: self.this = this
    def getVersion_(self): return _CppBlockUtils.Tx_getVersion_(self)
    def getNumTxIn_(self): return _CppBlockUtils.Tx_getNumTxIn_(self)
    def getNumTxOut_(self): return _CppBlockUtils.Tx_getNumTxOut_(self)
    def getTxInList_(self): return _CppBlockUtils.Tx_getTxInList_(self)
    def getTxOutList_(self): return _CppBlockUtils.Tx_getTxOutList_(self)
    def getLockTime_(self): return _CppBlockUtils.Tx_getLockTime_(self)
    def getNumBytes(self): return _CppBlockUtils.Tx_getNumBytes(self)
    def getHeaderPtr(self): return _CppBlockUtils.Tx_getHeaderPtr(self)
    def getHeaderRefPtr(self): return _CppBlockUtils.Tx_getHeaderRefPtr(self)
    def createOutPoint(self, *args): return _CppBlockUtils.Tx_createOutPoint(self, *args)
    def serialize(self, *args): return _CppBlockUtils.Tx_serialize(self, *args)
    def unserialize(self, *args): return _CppBlockUtils.Tx_unserialize(self, *args)
    __swig_destroy__ = _CppBlockUtils.delete_Tx
    __del__ = lambda self : None;
Tx_swigregister = _CppBlockUtils.Tx_swigregister
Tx_swigregister(Tx)

class UnspentTxOut:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, UnspentTxOut, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, UnspentTxOut, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _CppBlockUtils.new_UnspentTxOut(*args)
        try: self.this.append(this)
        except: self.this = this
    def init(self, *args): return _CppBlockUtils.UnspentTxOut_init(self, *args)
    def getTxHash(self): return _CppBlockUtils.UnspentTxOut_getTxHash(self)
    def getTxOutIndex(self): return _CppBlockUtils.UnspentTxOut_getTxOutIndex(self)
    def getValue(self): return _CppBlockUtils.UnspentTxOut_getValue(self)
    def getTxHeight(self): return _CppBlockUtils.UnspentTxOut_getTxHeight(self)
    def getNumConfirm(self): return _CppBlockUtils.UnspentTxOut_getNumConfirm(self)
    def getScript(self): return _CppBlockUtils.UnspentTxOut_getScript(self)
    def getRecipientAddr(self): return _CppBlockUtils.UnspentTxOut_getRecipientAddr(self)
    def updateNumConfirm(self, *args): return _CppBlockUtils.UnspentTxOut_updateNumConfirm(self, *args)
    __swig_getmethods__["CompareNaive"] = lambda x: _CppBlockUtils.UnspentTxOut_CompareNaive
    __swig_getmethods__["CompareTech1"] = lambda x: _CppBlockUtils.UnspentTxOut_CompareTech1
    __swig_getmethods__["CompareTech2"] = lambda x: _CppBlockUtils.UnspentTxOut_CompareTech2
    __swig_getmethods__["CompareTech3"] = lambda x: _CppBlockUtils.UnspentTxOut_CompareTech3
    __swig_getmethods__["sortTxOutVect"] = lambda x: _CppBlockUtils.UnspentTxOut_sortTxOutVect
    def pprintOneLine(self, *args): return _CppBlockUtils.UnspentTxOut_pprintOneLine(self, *args)
    __swig_setmethods__["txHash_"] = _CppBlockUtils.UnspentTxOut_txHash__set
    __swig_getmethods__["txHash_"] = _CppBlockUtils.UnspentTxOut_txHash__get
    __swig_setmethods__["txOutIndex_"] = _CppBlockUtils.UnspentTxOut_txOutIndex__set
    __swig_getmethods__["txOutIndex_"] = _CppBlockUtils.UnspentTxOut_txOutIndex__get
    __swig_setmethods__["txHeight_"] = _CppBlockUtils.UnspentTxOut_txHeight__set
    __swig_getmethods__["txHeight_"] = _CppBlockUtils.UnspentTxOut_txHeight__get
    __swig_setmethods__["value_"] = _CppBlockUtils.UnspentTxOut_value__set
    __swig_getmethods__["value_"] = _CppBlockUtils.UnspentTxOut_value__get
    __swig_setmethods__["script_"] = _CppBlockUtils.UnspentTxOut_script__set
    __swig_getmethods__["script_"] = _CppBlockUtils.UnspentTxOut_script__get
    __swig_setmethods__["numConfirm_"] = _CppBlockUtils.UnspentTxOut_numConfirm__set
    __swig_getmethods__["numConfirm_"] = _CppBlockUtils.UnspentTxOut_numConfirm__get
    __swig_setmethods__["targetTxAmount_"] = _CppBlockUtils.UnspentTxOut_targetTxAmount__set
    __swig_getmethods__["targetTxAmount_"] = _CppBlockUtils.UnspentTxOut_targetTxAmount__get
    __swig_destroy__ = _CppBlockUtils.delete_UnspentTxOut
    __del__ = lambda self : None;
UnspentTxOut_swigregister = _CppBlockUtils.UnspentTxOut_swigregister
UnspentTxOut_swigregister(UnspentTxOut)

def UnspentTxOut_CompareNaive(*args):
  return _CppBlockUtils.UnspentTxOut_CompareNaive(*args)
UnspentTxOut_CompareNaive = _CppBlockUtils.UnspentTxOut_CompareNaive

def UnspentTxOut_CompareTech1(*args):
  return _CppBlockUtils.UnspentTxOut_CompareTech1(*args)
UnspentTxOut_CompareTech1 = _CppBlockUtils.UnspentTxOut_CompareTech1

def UnspentTxOut_CompareTech2(*args):
  return _CppBlockUtils.UnspentTxOut_CompareTech2(*args)
UnspentTxOut_CompareTech2 = _CppBlockUtils.UnspentTxOut_CompareTech2

def UnspentTxOut_CompareTech3(*args):
  return _CppBlockUtils.UnspentTxOut_CompareTech3(*args)
UnspentTxOut_CompareTech3 = _CppBlockUtils.UnspentTxOut_CompareTech3

def UnspentTxOut_sortTxOutVect(*args):
  return _CppBlockUtils.UnspentTxOut_sortTxOutVect(*args)
UnspentTxOut_sortTxOutVect = _CppBlockUtils.UnspentTxOut_sortTxOutVect

class BlockHeaderRef:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, BlockHeaderRef, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, BlockHeaderRef, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _CppBlockUtils.new_BlockHeaderRef(*args)
        try: self.this.append(this)
        except: self.this = this
    def unserialize_1_(self, *args): return _CppBlockUtils.BlockHeaderRef_unserialize_1_(self, *args)
    def getVersion(self): return _CppBlockUtils.BlockHeaderRef_getVersion(self)
    def getThisHash(self): return _CppBlockUtils.BlockHeaderRef_getThisHash(self)
    def getPrevHash(self): return _CppBlockUtils.BlockHeaderRef_getPrevHash(self)
    def getNextHash(self): return _CppBlockUtils.BlockHeaderRef_getNextHash(self)
    def getMerkleRoot(self): return _CppBlockUtils.BlockHeaderRef_getMerkleRoot(self)
    def getDiffBits(self): return _CppBlockUtils.BlockHeaderRef_getDiffBits(self)
    def getTimestamp(self): return _CppBlockUtils.BlockHeaderRef_getTimestamp(self)
    def getNonce(self): return _CppBlockUtils.BlockHeaderRef_getNonce(self)
    def getBlockHeight(self): return _CppBlockUtils.BlockHeaderRef_getBlockHeight(self)
    def isMainBranch(self): return _CppBlockUtils.BlockHeaderRef_isMainBranch(self)
    def isOrphan(self): return _CppBlockUtils.BlockHeaderRef_isOrphan(self)
    def getDifficulty(self): return _CppBlockUtils.BlockHeaderRef_getDifficulty(self)
    def getDifficultySum(self): return _CppBlockUtils.BlockHeaderRef_getDifficultySum(self)
    def getThisHashRef(self): return _CppBlockUtils.BlockHeaderRef_getThisHashRef(self)
    def getPrevHashRef(self): return _CppBlockUtils.BlockHeaderRef_getPrevHashRef(self)
    def getNextHashRef(self): return _CppBlockUtils.BlockHeaderRef_getNextHashRef(self)
    def getMerkleRootRef(self): return _CppBlockUtils.BlockHeaderRef_getMerkleRootRef(self)
    def getDiffBitsRef(self): return _CppBlockUtils.BlockHeaderRef_getDiffBitsRef(self)
    def getBlkStartByte(self): return _CppBlockUtils.BlockHeaderRef_getBlkStartByte(self)
    def getNumTx(self): return _CppBlockUtils.BlockHeaderRef_getNumTx(self)
    def getPtr(self): return _CppBlockUtils.BlockHeaderRef_getPtr(self)
    def getSize(self): return _CppBlockUtils.BlockHeaderRef_getSize(self)
    def isInitialized(self): return _CppBlockUtils.BlockHeaderRef_isInitialized(self)
    def getBlockSize(self): return _CppBlockUtils.BlockHeaderRef_getBlockSize(self)
    def getTxRefPtrList(self): return _CppBlockUtils.BlockHeaderRef_getTxRefPtrList(self)
    def getTxHashList(self): return _CppBlockUtils.BlockHeaderRef_getTxHashList(self)
    def calcMerkleRoot(self, treeOut = None): return _CppBlockUtils.BlockHeaderRef_calcMerkleRoot(self, treeOut)
    def verifyMerkleRoot(self): return _CppBlockUtils.BlockHeaderRef_verifyMerkleRoot(self)
    def verifyIntegrity(self): return _CppBlockUtils.BlockHeaderRef_verifyIntegrity(self)
    def getCopy(self): return _CppBlockUtils.BlockHeaderRef_getCopy(self)
    def pprint(self, *args): return _CppBlockUtils.BlockHeaderRef_pprint(self, *args)
    def pprintAlot(self, *args): return _CppBlockUtils.BlockHeaderRef_pprintAlot(self, *args)
    def serialize(self): return _CppBlockUtils.BlockHeaderRef_serialize(self)
    def serializeRef(self): return _CppBlockUtils.BlockHeaderRef_serializeRef(self)
    def serializeWholeBlock(self, *args): return _CppBlockUtils.BlockHeaderRef_serializeWholeBlock(self, *args)
    def unserialize(self, *args): return _CppBlockUtils.BlockHeaderRef_unserialize(self, *args)
    __swig_destroy__ = _CppBlockUtils.delete_BlockHeaderRef
    __del__ = lambda self : None;
BlockHeaderRef_swigregister = _CppBlockUtils.BlockHeaderRef_swigregister
BlockHeaderRef_swigregister(BlockHeaderRef)

class OutPointRef:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, OutPointRef, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, OutPointRef, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _CppBlockUtils.new_OutPointRef(*args)
        try: self.this.append(this)
        except: self.this = this
    def getPtr(self): return _CppBlockUtils.OutPointRef_getPtr(self)
    def getSize(self): return _CppBlockUtils.OutPointRef_getSize(self)
    def getCopy(self): return _CppBlockUtils.OutPointRef_getCopy(self)
    def getTxHash(self): return _CppBlockUtils.OutPointRef_getTxHash(self)
    def getTxHashRef(self): return _CppBlockUtils.OutPointRef_getTxHashRef(self)
    def getTxOutIndex(self): return _CppBlockUtils.OutPointRef_getTxOutIndex(self)
    def serialize(self): return _CppBlockUtils.OutPointRef_serialize(self)
    def serializeRef(self): return _CppBlockUtils.OutPointRef_serializeRef(self)
    def unserialize(self, *args): return _CppBlockUtils.OutPointRef_unserialize(self, *args)
    __swig_destroy__ = _CppBlockUtils.delete_OutPointRef
    __del__ = lambda self : None;
OutPointRef_swigregister = _CppBlockUtils.OutPointRef_swigregister
OutPointRef_swigregister(OutPointRef)

class TxInRef:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, TxInRef, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, TxInRef, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _CppBlockUtils.new_TxInRef(*args)
        try: self.this.append(this)
        except: self.this = this
    def getPtr(self): return _CppBlockUtils.TxInRef_getPtr(self)
    def getSize(self): return _CppBlockUtils.TxInRef_getSize(self)
    def isStandard(self): return _CppBlockUtils.TxInRef_isStandard(self)
    def isCoinbase(self): return _CppBlockUtils.TxInRef_isCoinbase(self)
    def isInitialized(self): return _CppBlockUtils.TxInRef_isInitialized(self)
    def getScriptType(self): return _CppBlockUtils.TxInRef_getScriptType(self)
    def getScriptOffset(self): return _CppBlockUtils.TxInRef_getScriptOffset(self)
    def getCopy(self): return _CppBlockUtils.TxInRef_getCopy(self)
    def getParentTxPtr(self): return _CppBlockUtils.TxInRef_getParentTxPtr(self)
    def getIndex(self): return _CppBlockUtils.TxInRef_getIndex(self)
    def setParentTx(self, *args): return _CppBlockUtils.TxInRef_setParentTx(self, *args)
    def getSequence(self): return _CppBlockUtils.TxInRef_getSequence(self)
    def getScriptSize(self): return _CppBlockUtils.TxInRef_getScriptSize(self)
    def getOutPoint(self): return _CppBlockUtils.TxInRef_getOutPoint(self)
    def getOutPointRef(self): return _CppBlockUtils.TxInRef_getOutPointRef(self)
    def getScript(self): return _CppBlockUtils.TxInRef_getScript(self)
    def getScriptRef(self): return _CppBlockUtils.TxInRef_getScriptRef(self)
    def isScriptStandard(self): return _CppBlockUtils.TxInRef_isScriptStandard(self)
    def isScriptCoinbase(self): return _CppBlockUtils.TxInRef_isScriptCoinbase(self)
    def isScriptSpendCB(self): return _CppBlockUtils.TxInRef_isScriptSpendCB(self)
    def isScriptUnknown(self): return _CppBlockUtils.TxInRef_isScriptUnknown(self)
    def serialize(self): return _CppBlockUtils.TxInRef_serialize(self)
    def serializeRef(self): return _CppBlockUtils.TxInRef_serializeRef(self)
    def unserialize(self, *args): return _CppBlockUtils.TxInRef_unserialize(self, *args)
    def getSenderAddrIfAvailable(self, *args): return _CppBlockUtils.TxInRef_getSenderAddrIfAvailable(self, *args)
    def pprint(self, *args): return _CppBlockUtils.TxInRef_pprint(self, *args)
    __swig_destroy__ = _CppBlockUtils.delete_TxInRef
    __del__ = lambda self : None;
TxInRef_swigregister = _CppBlockUtils.TxInRef_swigregister
TxInRef_swigregister(TxInRef)

class TxOutRef:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, TxOutRef, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, TxOutRef, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _CppBlockUtils.new_TxOutRef(*args)
        try: self.this.append(this)
        except: self.this = this
    def getPtr(self): return _CppBlockUtils.TxOutRef_getPtr(self)
    def getSize(self): return _CppBlockUtils.TxOutRef_getSize(self)
    def getValue(self): return _CppBlockUtils.TxOutRef_getValue(self)
    def isStandard(self): return _CppBlockUtils.TxOutRef_isStandard(self)
    def isInitialized(self): return _CppBlockUtils.TxOutRef_isInitialized(self)
    def getParentTxPtr(self): return _CppBlockUtils.TxOutRef_getParentTxPtr(self)
    def getIndex(self): return _CppBlockUtils.TxOutRef_getIndex(self)
    def setParentTx(self, *args): return _CppBlockUtils.TxOutRef_setParentTx(self, *args)
    def getScriptType(self): return _CppBlockUtils.TxOutRef_getScriptType(self)
    def getScriptSize(self): return _CppBlockUtils.TxOutRef_getScriptSize(self)
    def getRecipientAddr(self): return _CppBlockUtils.TxOutRef_getRecipientAddr(self)
    def getRecipientAddrRef(self): return _CppBlockUtils.TxOutRef_getRecipientAddrRef(self)
    def getScript(self): return _CppBlockUtils.TxOutRef_getScript(self)
    def getScriptRef(self): return _CppBlockUtils.TxOutRef_getScriptRef(self)
    def isScriptStandard(self): return _CppBlockUtils.TxOutRef_isScriptStandard(self)
    def isScriptCoinbase(self): return _CppBlockUtils.TxOutRef_isScriptCoinbase(self)
    def isScriptUnknown(self): return _CppBlockUtils.TxOutRef_isScriptUnknown(self)
    def serialize(self): return _CppBlockUtils.TxOutRef_serialize(self)
    def serializeRef(self): return _CppBlockUtils.TxOutRef_serializeRef(self)
    def unserialize(self, *args): return _CppBlockUtils.TxOutRef_unserialize(self, *args)
    def getCopy(self): return _CppBlockUtils.TxOutRef_getCopy(self)
    def pprint(self, *args): return _CppBlockUtils.TxOutRef_pprint(self, *args)
    __swig_destroy__ = _CppBlockUtils.delete_TxOutRef
    __del__ = lambda self : None;
TxOutRef_swigregister = _CppBlockUtils.TxOutRef_swigregister
TxOutRef_swigregister(TxOutRef)

class TxRef:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, TxRef, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, TxRef, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _CppBlockUtils.new_TxRef(*args)
        try: self.this.append(this)
        except: self.this = this
    def getPtr(self): return _CppBlockUtils.TxRef_getPtr(self)
    def getSize(self): return _CppBlockUtils.TxRef_getSize(self)
    def getVersion(self): return _CppBlockUtils.TxRef_getVersion(self)
    def getNumTxIn(self): return _CppBlockUtils.TxRef_getNumTxIn(self)
    def getNumTxOut(self): return _CppBlockUtils.TxRef_getNumTxOut(self)
    def getThisHash(self): return _CppBlockUtils.TxRef_getThisHash(self)
    def getThisHashRef(self): return _CppBlockUtils.TxRef_getThisHashRef(self)
    def setMainBranch(self, b = True): return _CppBlockUtils.TxRef_setMainBranch(self, b)
    def isMainBranch(self): return _CppBlockUtils.TxRef_isMainBranch(self)
    def getTxStartByte(self): return _CppBlockUtils.TxRef_getTxStartByte(self)
    def setTxStartByte(self, *args): return _CppBlockUtils.TxRef_setTxStartByte(self, *args)
    def getTxInOffset(self, *args): return _CppBlockUtils.TxRef_getTxInOffset(self, *args)
    def getTxOutOffset(self, *args): return _CppBlockUtils.TxRef_getTxOutOffset(self, *args)
    def createFromStr(self, *args): return _CppBlockUtils.TxRef_createFromStr(self, *args)
    def getCopy(self): return _CppBlockUtils.TxRef_getCopy(self)
    def getHeaderPtr(self): return _CppBlockUtils.TxRef_getHeaderPtr(self)
    def setHeaderPtr(self, *args): return _CppBlockUtils.TxRef_setHeaderPtr(self, *args)
    def serialize(self): return _CppBlockUtils.TxRef_serialize(self)
    def serializeRef(self): return _CppBlockUtils.TxRef_serializeRef(self)
    def unserialize(self, *args): return _CppBlockUtils.TxRef_unserialize(self, *args)
    def getLockTime(self): return _CppBlockUtils.TxRef_getLockTime(self)
    def getSumOfOutputs(self): return _CppBlockUtils.TxRef_getSumOfOutputs(self)
    def getTxInRef(self, *args): return _CppBlockUtils.TxRef_getTxInRef(self, *args)
    def getTxOutRef(self, *args): return _CppBlockUtils.TxRef_getTxOutRef(self, *args)
    def getBlockTimestamp(self): return _CppBlockUtils.TxRef_getBlockTimestamp(self)
    def getBlockHeight(self): return _CppBlockUtils.TxRef_getBlockHeight(self)
    def getBlockTxIndex(self): return _CppBlockUtils.TxRef_getBlockTxIndex(self)
    def pprint(self, *args): return _CppBlockUtils.TxRef_pprint(self, *args)
    def pprintAlot(self, *args): return _CppBlockUtils.TxRef_pprintAlot(self, *args)
    __swig_destroy__ = _CppBlockUtils.delete_TxRef
    __del__ = lambda self : None;
TxRef_swigregister = _CppBlockUtils.TxRef_swigregister
TxRef_swigregister(TxRef)

TX_0_UNCONFIRMED = _CppBlockUtils.TX_0_UNCONFIRMED
TX_NOT_EXIST = _CppBlockUtils.TX_NOT_EXIST
TX_OFF_MAIN_BRANCH = _CppBlockUtils.TX_OFF_MAIN_BRANCH
MIN_CONFIRMATIONS = _CppBlockUtils.MIN_CONFIRMATIONS
COINBASE_MATURITY = _CppBlockUtils.COINBASE_MATURITY
class TxIOPair:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, TxIOPair, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, TxIOPair, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _CppBlockUtils.new_TxIOPair(*args)
        try: self.this.append(this)
        except: self.this = this
    def hasTxOut(self): return _CppBlockUtils.TxIOPair_hasTxOut(self)
    def hasTxIn(self): return _CppBlockUtils.TxIOPair_hasTxIn(self)
    def hasTxOutInMain(self): return _CppBlockUtils.TxIOPair_hasTxOutInMain(self)
    def hasTxInInMain(self): return _CppBlockUtils.TxIOPair_hasTxInInMain(self)
    def hasTxOutZC(self): return _CppBlockUtils.TxIOPair_hasTxOutZC(self)
    def hasTxInZC(self): return _CppBlockUtils.TxIOPair_hasTxInZC(self)
    def hasValue(self): return _CppBlockUtils.TxIOPair_hasValue(self)
    def getValue(self): return _CppBlockUtils.TxIOPair_getValue(self)
    def getTxOutRef(self): return _CppBlockUtils.TxIOPair_getTxOutRef(self)
    def getTxInRef(self): return _CppBlockUtils.TxIOPair_getTxInRef(self)
    def getTxOutRefZC(self): return _CppBlockUtils.TxIOPair_getTxOutRefZC(self)
    def getTxInRefZC(self): return _CppBlockUtils.TxIOPair_getTxInRefZC(self)
    def getTxRefOfOutput(self): return _CppBlockUtils.TxIOPair_getTxRefOfOutput(self)
    def getTxRefOfInput(self): return _CppBlockUtils.TxIOPair_getTxRefOfInput(self)
    def getOutPoint(self): return _CppBlockUtils.TxIOPair_getOutPoint(self)
    def reassessValidity(self): return _CppBlockUtils.TxIOPair_reassessValidity(self)
    def isTxOutFromSelf(self): return _CppBlockUtils.TxIOPair_isTxOutFromSelf(self)
    def setTxOutFromSelf(self, isTrue = True): return _CppBlockUtils.TxIOPair_setTxOutFromSelf(self, isTrue)
    def isFromCoinbase(self): return _CppBlockUtils.TxIOPair_isFromCoinbase(self)
    def setFromCoinbase(self, isTrue = True): return _CppBlockUtils.TxIOPair_setFromCoinbase(self, isTrue)
    def getTxHashOfInput(self): return _CppBlockUtils.TxIOPair_getTxHashOfInput(self)
    def getTxHashOfOutput(self): return _CppBlockUtils.TxIOPair_getTxHashOfOutput(self)
    def setTxInRef(self, *args): return _CppBlockUtils.TxIOPair_setTxInRef(self, *args)
    def setTxOutRef(self, *args): return _CppBlockUtils.TxIOPair_setTxOutRef(self, *args)
    def isSourceUnknown(self): return _CppBlockUtils.TxIOPair_isSourceUnknown(self)
    def isStandardTxOutScript(self): return _CppBlockUtils.TxIOPair_isStandardTxOutScript(self)
    def isSpent(self): return _CppBlockUtils.TxIOPair_isSpent(self)
    def isUnspent(self): return _CppBlockUtils.TxIOPair_isUnspent(self)
    def isSpendable(self, currBlk = 0): return _CppBlockUtils.TxIOPair_isSpendable(self, currBlk)
    def isMineButUnconfirmed(self, *args): return _CppBlockUtils.TxIOPair_isMineButUnconfirmed(self, *args)
    def clearZCFields(self): return _CppBlockUtils.TxIOPair_clearZCFields(self)
    def pprintOneLine(self): return _CppBlockUtils.TxIOPair_pprintOneLine(self)
    __swig_destroy__ = _CppBlockUtils.delete_TxIOPair
    __del__ = lambda self : None;
TxIOPair_swigregister = _CppBlockUtils.TxIOPair_swigregister
TxIOPair_swigregister(TxIOPair)

class LedgerEntry:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, LedgerEntry, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, LedgerEntry, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _CppBlockUtils.new_LedgerEntry(*args)
        try: self.this.append(this)
        except: self.this = this
    def getAddrStr20(self): return _CppBlockUtils.LedgerEntry_getAddrStr20(self)
    def getValue(self): return _CppBlockUtils.LedgerEntry_getValue(self)
    def getBlockNum(self): return _CppBlockUtils.LedgerEntry_getBlockNum(self)
    def getTxHash(self): return _CppBlockUtils.LedgerEntry_getTxHash(self)
    def getIndex(self): return _CppBlockUtils.LedgerEntry_getIndex(self)
    def getTxTime(self): return _CppBlockUtils.LedgerEntry_getTxTime(self)
    def isValid(self): return _CppBlockUtils.LedgerEntry_isValid(self)
    def isSentToSelf(self): return _CppBlockUtils.LedgerEntry_isSentToSelf(self)
    def isChangeBack(self): return _CppBlockUtils.LedgerEntry_isChangeBack(self)
    def setAddr20(self, *args): return _CppBlockUtils.LedgerEntry_setAddr20(self, *args)
    def setValid(self, b = True): return _CppBlockUtils.LedgerEntry_setValid(self, b)
    def changeBlkNum(self, *args): return _CppBlockUtils.LedgerEntry_changeBlkNum(self, *args)
    def __lt__(self, *args): return _CppBlockUtils.LedgerEntry___lt__(self, *args)
    def __eq__(self, *args): return _CppBlockUtils.LedgerEntry___eq__(self, *args)
    def pprint(self): return _CppBlockUtils.LedgerEntry_pprint(self)
    def pprintOneLine(self): return _CppBlockUtils.LedgerEntry_pprintOneLine(self)
    __swig_destroy__ = _CppBlockUtils.delete_LedgerEntry
    __del__ = lambda self : None;
LedgerEntry_swigregister = _CppBlockUtils.LedgerEntry_swigregister
LedgerEntry_swigregister(LedgerEntry)

class BtcAddress:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, BtcAddress, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, BtcAddress, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _CppBlockUtils.new_BtcAddress(*args)
        try: self.this.append(this)
        except: self.this = this
    def getAddrStr20(self): return _CppBlockUtils.BtcAddress_getAddrStr20(self)
    def getFirstBlockNum(self): return _CppBlockUtils.BtcAddress_getFirstBlockNum(self)
    def getFirstTimestamp(self): return _CppBlockUtils.BtcAddress_getFirstTimestamp(self)
    def getLastBlockNum(self): return _CppBlockUtils.BtcAddress_getLastBlockNum(self)
    def getLastTimestamp(self): return _CppBlockUtils.BtcAddress_getLastTimestamp(self)
    def setFirstBlockNum(self, *args): return _CppBlockUtils.BtcAddress_setFirstBlockNum(self, *args)
    def setFirstTimestamp(self, *args): return _CppBlockUtils.BtcAddress_setFirstTimestamp(self, *args)
    def setLastBlockNum(self, *args): return _CppBlockUtils.BtcAddress_setLastBlockNum(self, *args)
    def setLastTimestamp(self, *args): return _CppBlockUtils.BtcAddress_setLastTimestamp(self, *args)
    def isUnused(self): return _CppBlockUtils.BtcAddress_isUnused(self)
    def setUnused(self): return _CppBlockUtils.BtcAddress_setUnused(self)
    def setAddrStr20(self, *args): return _CppBlockUtils.BtcAddress_setAddrStr20(self, *args)
    def sortLedger(self): return _CppBlockUtils.BtcAddress_sortLedger(self)
    def removeInvalidEntries(self): return _CppBlockUtils.BtcAddress_removeInvalidEntries(self)
    def getFullBalance(self): return _CppBlockUtils.BtcAddress_getFullBalance(self)
    def getSpendableBalance(self, currBlk = 0): return _CppBlockUtils.BtcAddress_getSpendableBalance(self, currBlk)
    def getUnconfirmedBalance(self, *args): return _CppBlockUtils.BtcAddress_getUnconfirmedBalance(self, *args)
    def getFullTxOutList(self, currBlk = 0): return _CppBlockUtils.BtcAddress_getFullTxOutList(self, currBlk)
    def getSpendableTxOutList(self, currBlk = 0): return _CppBlockUtils.BtcAddress_getSpendableTxOutList(self, currBlk)
    def clearZeroConfPool(self): return _CppBlockUtils.BtcAddress_clearZeroConfPool(self)
    def getTxLedger(self): return _CppBlockUtils.BtcAddress_getTxLedger(self)
    def getZeroConfLedger(self): return _CppBlockUtils.BtcAddress_getZeroConfLedger(self)
    def getTxIOList(self): return _CppBlockUtils.BtcAddress_getTxIOList(self)
    def addTxIO(self, *args): return _CppBlockUtils.BtcAddress_addTxIO(self, *args)
    def addLedgerEntry(self, *args): return _CppBlockUtils.BtcAddress_addLedgerEntry(self, *args)
    def pprintLedger(self): return _CppBlockUtils.BtcAddress_pprintLedger(self)
    __swig_destroy__ = _CppBlockUtils.delete_BtcAddress
    __del__ = lambda self : None;
BtcAddress_swigregister = _CppBlockUtils.BtcAddress_swigregister
BtcAddress_swigregister(BtcAddress)

class BtcWallet:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, BtcWallet, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, BtcWallet, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _CppBlockUtils.new_BtcWallet()
        try: self.this.append(this)
        except: self.this = this
    def addAddress(self, *args): return _CppBlockUtils.BtcWallet_addAddress(self, *args)
    def addAddress_BtcAddress_(self, *args): return _CppBlockUtils.BtcWallet_addAddress_BtcAddress_(self, *args)
    def addAddress_1_(self, *args): return _CppBlockUtils.BtcWallet_addAddress_1_(self, *args)
    def addAddress_3_(self, *args): return _CppBlockUtils.BtcWallet_addAddress_3_(self, *args)
    def addAddress_5_(self, *args): return _CppBlockUtils.BtcWallet_addAddress_5_(self, *args)
    def hasAddr(self, *args): return _CppBlockUtils.BtcWallet_hasAddr(self, *args)
    def isMineBulkFilter(self, *args): return _CppBlockUtils.BtcWallet_isMineBulkFilter(self, *args)
    def scanTx(self, *args): return _CppBlockUtils.BtcWallet_scanTx(self, *args)
    def scanNonStdTx(self, *args): return _CppBlockUtils.BtcWallet_scanNonStdTx(self, *args)
    def initialScanWalletFilter(self, *args): return _CppBlockUtils.BtcWallet_initialScanWalletFilter(self, *args)
    def getFullBalance(self): return _CppBlockUtils.BtcWallet_getFullBalance(self)
    def getSpendableBalance(self, currBlk = 0): return _CppBlockUtils.BtcWallet_getSpendableBalance(self, currBlk)
    def getUnconfirmedBalance(self, *args): return _CppBlockUtils.BtcWallet_getUnconfirmedBalance(self, *args)
    def getFullTxOutList(self, currBlk = 0): return _CppBlockUtils.BtcWallet_getFullTxOutList(self, currBlk)
    def getSpendableTxOutList(self, currBlk = 0): return _CppBlockUtils.BtcWallet_getSpendableTxOutList(self, currBlk)
    def clearZeroConfPool(self): return _CppBlockUtils.BtcWallet_clearZeroConfPool(self)
    def getNumAddr(self): return _CppBlockUtils.BtcWallet_getNumAddr(self)
    def getAddrByIndex(self, *args): return _CppBlockUtils.BtcWallet_getAddrByIndex(self, *args)
    def getAddrByHash160(self, *args): return _CppBlockUtils.BtcWallet_getAddrByHash160(self, *args)
    def sortLedger(self): return _CppBlockUtils.BtcWallet_sortLedger(self)
    def removeInvalidEntries(self): return _CppBlockUtils.BtcWallet_removeInvalidEntries(self)
    def getZeroConfLedger(self, addr160 = None): return _CppBlockUtils.BtcWallet_getZeroConfLedger(self, addr160)
    def getTxLedger(self, addr160 = None): return _CppBlockUtils.BtcWallet_getTxLedger(self, addr160)
    def getTxIOMap(self): return _CppBlockUtils.BtcWallet_getTxIOMap(self)
    def getNonStdTxIO(self): return _CppBlockUtils.BtcWallet_getNonStdTxIO(self)
    def isOutPointMine(self, *args): return _CppBlockUtils.BtcWallet_isOutPointMine(self, *args)
    def pprintLedger(self): return _CppBlockUtils.BtcWallet_pprintLedger(self)
    def pprintAlot(self, topBlk = 0, withAddr = False): return _CppBlockUtils.BtcWallet_pprintAlot(self, topBlk, withAddr)
    __swig_destroy__ = _CppBlockUtils.delete_BtcWallet
    __del__ = lambda self : None;
BtcWallet_swigregister = _CppBlockUtils.BtcWallet_swigregister
BtcWallet_swigregister(BtcWallet)

class ZeroConfData:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ZeroConfData, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ZeroConfData, name)
    __repr__ = _swig_repr
    __swig_setmethods__["txref_"] = _CppBlockUtils.ZeroConfData_txref__set
    __swig_getmethods__["txref_"] = _CppBlockUtils.ZeroConfData_txref__get
    __swig_setmethods__["txtime_"] = _CppBlockUtils.ZeroConfData_txtime__set
    __swig_getmethods__["txtime_"] = _CppBlockUtils.ZeroConfData_txtime__get
    __swig_setmethods__["iter_"] = _CppBlockUtils.ZeroConfData_iter__set
    __swig_getmethods__["iter_"] = _CppBlockUtils.ZeroConfData_iter__get
    def __init__(self): 
        this = _CppBlockUtils.new_ZeroConfData()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _CppBlockUtils.delete_ZeroConfData
    __del__ = lambda self : None;
ZeroConfData_swigregister = _CppBlockUtils.ZeroConfData_swigregister
ZeroConfData_swigregister(ZeroConfData)

BDM_MODE_FULL_BLOCKCHAIN = _CppBlockUtils.BDM_MODE_FULL_BLOCKCHAIN
BDM_MODE_LIGHT_STORAGE = _CppBlockUtils.BDM_MODE_LIGHT_STORAGE
BDM_MODE_NO_STORAGE = _CppBlockUtils.BDM_MODE_NO_STORAGE
BDM_MODE_COUNT = _CppBlockUtils.BDM_MODE_COUNT
ADD_BLOCK_SUCCEEDED = _CppBlockUtils.ADD_BLOCK_SUCCEEDED
ADD_BLOCK_NEW_TOP_BLOCK = _CppBlockUtils.ADD_BLOCK_NEW_TOP_BLOCK
ADD_BLOCK_CAUSED_REORG = _CppBlockUtils.ADD_BLOCK_CAUSED_REORG
class BlockDataManager_MMAP:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, BlockDataManager_MMAP, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, BlockDataManager_MMAP, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __swig_getmethods__["GetInstance"] = lambda x: _CppBlockUtils.BlockDataManager_MMAP_GetInstance
    def isInitialized(self): return _CppBlockUtils.BlockDataManager_MMAP_isInitialized(self)
    def SetBtcNetworkParams(self, *args): return _CppBlockUtils.BlockDataManager_MMAP_SetBtcNetworkParams(self, *args)
    def SelectNetwork(self, *args): return _CppBlockUtils.BlockDataManager_MMAP_SelectNetwork(self, *args)
    def Reset(self): return _CppBlockUtils.BlockDataManager_MMAP_Reset(self)
    def getNumConfirmations(self, *args): return _CppBlockUtils.BlockDataManager_MMAP_getNumConfirmations(self, *args)
    def getTopBlockHeader(self): return _CppBlockUtils.BlockDataManager_MMAP_getTopBlockHeader(self)
    def getGenesisBlock(self): return _CppBlockUtils.BlockDataManager_MMAP_getGenesisBlock(self)
    def getHeaderByHeight(self, *args): return _CppBlockUtils.BlockDataManager_MMAP_getHeaderByHeight(self, *args)
    def getHeaderByHash(self, *args): return _CppBlockUtils.BlockDataManager_MMAP_getHeaderByHash(self, *args)
    def getTxByHash(self, *args): return _CppBlockUtils.BlockDataManager_MMAP_getTxByHash(self, *args)
    def getBlockfilePath(self): return _CppBlockUtils.BlockDataManager_MMAP_getBlockfilePath(self)
    def parseNewBlockData(self, *args): return _CppBlockUtils.BlockDataManager_MMAP_parseNewBlockData(self, *args)
    def addNewBlockData(self, *args): return _CppBlockUtils.BlockDataManager_MMAP_addNewBlockData(self, *args)
    def addNewBlockDataRef(self, *args): return _CppBlockUtils.BlockDataManager_MMAP_addNewBlockDataRef(self, *args)
    def reassessAfterReorg(self, *args): return _CppBlockUtils.BlockDataManager_MMAP_reassessAfterReorg(self, *args)
    def hasTxWithHash(self, *args): return _CppBlockUtils.BlockDataManager_MMAP_hasTxWithHash(self, *args)
    def hasHeaderWithHash(self, *args): return _CppBlockUtils.BlockDataManager_MMAP_hasHeaderWithHash(self, *args)
    def getNumBlocks(self): return _CppBlockUtils.BlockDataManager_MMAP_getNumBlocks(self)
    def getNumTx(self): return _CppBlockUtils.BlockDataManager_MMAP_getNumTx(self)
    def getHeadersNotOnMainChain(self): return _CppBlockUtils.BlockDataManager_MMAP_getHeadersNotOnMainChain(self)
    def prefixSearchHeaders(self, *args): return _CppBlockUtils.BlockDataManager_MMAP_prefixSearchHeaders(self, *args)
    def prefixSearchTx(self, *args): return _CppBlockUtils.BlockDataManager_MMAP_prefixSearchTx(self, *args)
    def prefixSearchAddress(self, *args): return _CppBlockUtils.BlockDataManager_MMAP_prefixSearchAddress(self, *args)
    def scanBlockchainForTx(self, *args): return _CppBlockUtils.BlockDataManager_MMAP_scanBlockchainForTx(self, *args)
    def scanRelevantTxForWallet(self, *args): return _CppBlockUtils.BlockDataManager_MMAP_scanRelevantTxForWallet(self, *args)
    def readBlkFile_FromScratch(self, *args): return _CppBlockUtils.BlockDataManager_MMAP_readBlkFile_FromScratch(self, *args)
    def readBlkFileUpdate(self, filename = ""): return _CppBlockUtils.BlockDataManager_MMAP_readBlkFileUpdate(self, filename)
    def verifyBlkFileIntegrity(self): return _CppBlockUtils.BlockDataManager_MMAP_verifyBlkFileIntegrity(self)
    def scanBlockchainForTx_FromScratch_AllAddr(self): return _CppBlockUtils.BlockDataManager_MMAP_scanBlockchainForTx_FromScratch_AllAddr(self)
    def findAllNonStdTx(self): return _CppBlockUtils.BlockDataManager_MMAP_findAllNonStdTx(self)
    def enableZeroConf(self, *args): return _CppBlockUtils.BlockDataManager_MMAP_enableZeroConf(self, *args)
    def disableZeroConf(self, *args): return _CppBlockUtils.BlockDataManager_MMAP_disableZeroConf(self, *args)
    def readZeroConfFile(self, *args): return _CppBlockUtils.BlockDataManager_MMAP_readZeroConfFile(self, *args)
    def addNewZeroConfTx(self, *args): return _CppBlockUtils.BlockDataManager_MMAP_addNewZeroConfTx(self, *args)
    def purgeZeroConfPool(self): return _CppBlockUtils.BlockDataManager_MMAP_purgeZeroConfPool(self)
    def pprintZeroConfPool(self): return _CppBlockUtils.BlockDataManager_MMAP_pprintZeroConfPool(self)
    def rewriteZeroConfFile(self): return _CppBlockUtils.BlockDataManager_MMAP_rewriteZeroConfFile(self)
    def rescanWalletZeroConf(self, *args): return _CppBlockUtils.BlockDataManager_MMAP_rescanWalletZeroConf(self, *args)
    def organizeChain(self, forceRebuild = False): return _CppBlockUtils.BlockDataManager_MMAP_organizeChain(self, forceRebuild)
    def isLastBlockReorg(self): return _CppBlockUtils.BlockDataManager_MMAP_isLastBlockReorg(self)
    def getTxJustInvalidated(self): return _CppBlockUtils.BlockDataManager_MMAP_getTxJustInvalidated(self)
    def getTxJustAffected(self): return _CppBlockUtils.BlockDataManager_MMAP_getTxJustAffected(self)
    def updateWalletAfterReorg(self, *args): return _CppBlockUtils.BlockDataManager_MMAP_updateWalletAfterReorg(self, *args)
    def updateWalletsAfterReorg(self, *args): return _CppBlockUtils.BlockDataManager_MMAP_updateWalletsAfterReorg(self, *args)
    def getPrevTxOut(self, *args): return _CppBlockUtils.BlockDataManager_MMAP_getPrevTxOut(self, *args)
    def getSenderAddr20(self, *args): return _CppBlockUtils.BlockDataManager_MMAP_getSenderAddr20(self, *args)
    def getSentValue(self, *args): return _CppBlockUtils.BlockDataManager_MMAP_getSentValue(self, *args)
    __swig_destroy__ = _CppBlockUtils.delete_BlockDataManager_MMAP
    __del__ = lambda self : None;
BlockDataManager_MMAP_swigregister = _CppBlockUtils.BlockDataManager_MMAP_swigregister
BlockDataManager_MMAP_swigregister(BlockDataManager_MMAP)

def BlockDataManager_MMAP_GetInstance():
  return _CppBlockUtils.BlockDataManager_MMAP_GetInstance()
BlockDataManager_MMAP_GetInstance = _CppBlockUtils.BlockDataManager_MMAP_GetInstance

class BlockDataManager:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, BlockDataManager, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, BlockDataManager, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _CppBlockUtils.new_BlockDataManager()
        try: self.this.append(this)
        except: self.this = this
    def getBDM(self): return _CppBlockUtils.BlockDataManager_getBDM(self)
    __swig_destroy__ = _CppBlockUtils.delete_BlockDataManager
    __del__ = lambda self : None;
BlockDataManager_swigregister = _CppBlockUtils.BlockDataManager_swigregister
BlockDataManager_swigregister(BlockDataManager)

HEADER_SIZE = _CppBlockUtils.HEADER_SIZE
CONVERTBTC = _CppBlockUtils.CONVERTBTC
TESTNET_MAGIC_BYTES = _CppBlockUtils.TESTNET_MAGIC_BYTES
TESTNET_GENESIS_HASH_HEX = _CppBlockUtils.TESTNET_GENESIS_HASH_HEX
TESTNET_GENESIS_TX_HASH_HEX = _CppBlockUtils.TESTNET_GENESIS_TX_HASH_HEX
MAINNET_MAGIC_BYTES = _CppBlockUtils.MAINNET_MAGIC_BYTES
MAINNET_GENESIS_HASH_HEX = _CppBlockUtils.MAINNET_GENESIS_HASH_HEX
MAINNET_GENESIS_TX_HASH_HEX = _CppBlockUtils.MAINNET_GENESIS_TX_HASH_HEX
TXOUT_SCRIPT_STANDARD = _CppBlockUtils.TXOUT_SCRIPT_STANDARD
TXOUT_SCRIPT_COINBASE = _CppBlockUtils.TXOUT_SCRIPT_COINBASE
TXOUT_SCRIPT_UNKNOWN = _CppBlockUtils.TXOUT_SCRIPT_UNKNOWN
TXIN_SCRIPT_STANDARD = _CppBlockUtils.TXIN_SCRIPT_STANDARD
TXIN_SCRIPT_COINBASE = _CppBlockUtils.TXIN_SCRIPT_COINBASE
TXIN_SCRIPT_SPENDCB = _CppBlockUtils.TXIN_SCRIPT_SPENDCB
TXIN_SCRIPT_UNKNOWN = _CppBlockUtils.TXIN_SCRIPT_UNKNOWN
OP_0 = _CppBlockUtils.OP_0
OP_FALSE = _CppBlockUtils.OP_FALSE
OP_PUSHDATA1 = _CppBlockUtils.OP_PUSHDATA1
OP_PUSHDATA2 = _CppBlockUtils.OP_PUSHDATA2
OP_PUSHDATA4 = _CppBlockUtils.OP_PUSHDATA4
OP_1NEGATE = _CppBlockUtils.OP_1NEGATE
OP_RESERVED = _CppBlockUtils.OP_RESERVED
OP_1 = _CppBlockUtils.OP_1
OP_TRUE = _CppBlockUtils.OP_TRUE
OP_2 = _CppBlockUtils.OP_2
OP_3 = _CppBlockUtils.OP_3
OP_4 = _CppBlockUtils.OP_4
OP_5 = _CppBlockUtils.OP_5
OP_6 = _CppBlockUtils.OP_6
OP_7 = _CppBlockUtils.OP_7
OP_8 = _CppBlockUtils.OP_8
OP_9 = _CppBlockUtils.OP_9
OP_10 = _CppBlockUtils.OP_10
OP_11 = _CppBlockUtils.OP_11
OP_12 = _CppBlockUtils.OP_12
OP_13 = _CppBlockUtils.OP_13
OP_14 = _CppBlockUtils.OP_14
OP_15 = _CppBlockUtils.OP_15
OP_16 = _CppBlockUtils.OP_16
OP_NOP = _CppBlockUtils.OP_NOP
OP_VER = _CppBlockUtils.OP_VER
OP_IF = _CppBlockUtils.OP_IF
OP_NOTIF = _CppBlockUtils.OP_NOTIF
OP_VERIF = _CppBlockUtils.OP_VERIF
OP_VERNOTIF = _CppBlockUtils.OP_VERNOTIF
OP_ELSE = _CppBlockUtils.OP_ELSE
OP_ENDIF = _CppBlockUtils.OP_ENDIF
OP_VERIFY = _CppBlockUtils.OP_VERIFY
OP_RETURN = _CppBlockUtils.OP_RETURN
OP_TOALTSTACK = _CppBlockUtils.OP_TOALTSTACK
OP_FROMALTSTACK = _CppBlockUtils.OP_FROMALTSTACK
OP_2DROP = _CppBlockUtils.OP_2DROP
OP_2DUP = _CppBlockUtils.OP_2DUP
OP_3DUP = _CppBlockUtils.OP_3DUP
OP_2OVER = _CppBlockUtils.OP_2OVER
OP_2ROT = _CppBlockUtils.OP_2ROT
OP_2SWAP = _CppBlockUtils.OP_2SWAP
OP_IFDUP = _CppBlockUtils.OP_IFDUP
OP_DEPTH = _CppBlockUtils.OP_DEPTH
OP_DROP = _CppBlockUtils.OP_DROP
OP_DUP = _CppBlockUtils.OP_DUP
OP_NIP = _CppBlockUtils.OP_NIP
OP_OVER = _CppBlockUtils.OP_OVER
OP_PICK = _CppBlockUtils.OP_PICK
OP_ROLL = _CppBlockUtils.OP_ROLL
OP_ROT = _CppBlockUtils.OP_ROT
OP_SWAP = _CppBlockUtils.OP_SWAP
OP_TUCK = _CppBlockUtils.OP_TUCK
OP_CAT = _CppBlockUtils.OP_CAT
OP_SUBSTR = _CppBlockUtils.OP_SUBSTR
OP_LEFT = _CppBlockUtils.OP_LEFT
OP_RIGHT = _CppBlockUtils.OP_RIGHT
OP_SIZE = _CppBlockUtils.OP_SIZE
OP_INVERT = _CppBlockUtils.OP_INVERT
OP_AND = _CppBlockUtils.OP_AND
OP_OR = _CppBlockUtils.OP_OR
OP_XOR = _CppBlockUtils.OP_XOR
OP_EQUAL = _CppBlockUtils.OP_EQUAL
OP_EQUALVERIFY = _CppBlockUtils.OP_EQUALVERIFY
OP_RESERVED1 = _CppBlockUtils.OP_RESERVED1
OP_RESERVED2 = _CppBlockUtils.OP_RESERVED2
OP_1ADD = _CppBlockUtils.OP_1ADD
OP_1SUB = _CppBlockUtils.OP_1SUB
OP_2MUL = _CppBlockUtils.OP_2MUL
OP_2DIV = _CppBlockUtils.OP_2DIV
OP_NEGATE = _CppBlockUtils.OP_NEGATE
OP_ABS = _CppBlockUtils.OP_ABS
OP_NOT = _CppBlockUtils.OP_NOT
OP_0NOTEQUAL = _CppBlockUtils.OP_0NOTEQUAL
OP_ADD = _CppBlockUtils.OP_ADD
OP_SUB = _CppBlockUtils.OP_SUB
OP_MUL = _CppBlockUtils.OP_MUL
OP_DIV = _CppBlockUtils.OP_DIV
OP_MOD = _CppBlockUtils.OP_MOD
OP_LSHIFT = _CppBlockUtils.OP_LSHIFT
OP_RSHIFT = _CppBlockUtils.OP_RSHIFT
OP_BOOLAND = _CppBlockUtils.OP_BOOLAND
OP_BOOLOR = _CppBlockUtils.OP_BOOLOR
OP_NUMEQUAL = _CppBlockUtils.OP_NUMEQUAL
OP_NUMEQUALVERIFY = _CppBlockUtils.OP_NUMEQUALVERIFY
OP_NUMNOTEQUAL = _CppBlockUtils.OP_NUMNOTEQUAL
OP_LESSTHAN = _CppBlockUtils.OP_LESSTHAN
OP_GREATERTHAN = _CppBlockUtils.OP_GREATERTHAN
OP_LESSTHANOREQUAL = _CppBlockUtils.OP_LESSTHANOREQUAL
OP_GREATERTHANOREQUAL = _CppBlockUtils.OP_GREATERTHANOREQUAL
OP_MIN = _CppBlockUtils.OP_MIN
OP_MAX = _CppBlockUtils.OP_MAX
OP_WITHIN = _CppBlockUtils.OP_WITHIN
OP_RIPEMD160 = _CppBlockUtils.OP_RIPEMD160
OP_SHA1 = _CppBlockUtils.OP_SHA1
OP_SHA256 = _CppBlockUtils.OP_SHA256
OP_HASH160 = _CppBlockUtils.OP_HASH160
OP_HASH256 = _CppBlockUtils.OP_HASH256
OP_CODESEPARATOR = _CppBlockUtils.OP_CODESEPARATOR
OP_CHECKSIG = _CppBlockUtils.OP_CHECKSIG
OP_CHECKSIGVERIFY = _CppBlockUtils.OP_CHECKSIGVERIFY
OP_CHECKMULTISIG = _CppBlockUtils.OP_CHECKMULTISIG
OP_CHECKMULTISIGVERIFY = _CppBlockUtils.OP_CHECKMULTISIGVERIFY
OP_NOP1 = _CppBlockUtils.OP_NOP1
OP_NOP2 = _CppBlockUtils.OP_NOP2
OP_NOP3 = _CppBlockUtils.OP_NOP3
OP_NOP4 = _CppBlockUtils.OP_NOP4
OP_NOP5 = _CppBlockUtils.OP_NOP5
OP_NOP6 = _CppBlockUtils.OP_NOP6
OP_NOP7 = _CppBlockUtils.OP_NOP7
OP_NOP8 = _CppBlockUtils.OP_NOP8
OP_NOP9 = _CppBlockUtils.OP_NOP9
OP_NOP10 = _CppBlockUtils.OP_NOP10
OP_PUBKEYHASH = _CppBlockUtils.OP_PUBKEYHASH
OP_PUBKEY = _CppBlockUtils.OP_PUBKEY
OP_INVALIDOPCODE = _CppBlockUtils.OP_INVALIDOPCODE
class BtcUtils:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, BtcUtils, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, BtcUtils, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _CppBlockUtils.new_BtcUtils()
        try: self.this.append(this)
        except: self.this = this
    def hash256(self, *args): return _CppBlockUtils.BtcUtils_hash256(self, *args)
    def hash160(self, *args): return _CppBlockUtils.BtcUtils_hash160(self, *args)
    __swig_setmethods__["BadAddress_"] = _CppBlockUtils.BtcUtils_BadAddress__set
    __swig_getmethods__["BadAddress_"] = _CppBlockUtils.BtcUtils_BadAddress__get
    __swig_setmethods__["EmptyHash_"] = _CppBlockUtils.BtcUtils_EmptyHash__set
    __swig_getmethods__["EmptyHash_"] = _CppBlockUtils.BtcUtils_EmptyHash__get
    __swig_getmethods__["readVarInt"] = lambda x: _CppBlockUtils.BtcUtils_readVarInt
    __swig_getmethods__["readVarIntLength"] = lambda x: _CppBlockUtils.BtcUtils_readVarIntLength
    __swig_getmethods__["calcVarIntSize"] = lambda x: _CppBlockUtils.BtcUtils_calcVarIntSize
    __swig_getmethods__["getHash256_NoSafetyCheck"] = lambda x: _CppBlockUtils.BtcUtils_getHash256_NoSafetyCheck
    __swig_getmethods__["getHash256"] = lambda x: _CppBlockUtils.BtcUtils_getHash256
    __swig_getmethods__["getHash160_NoSafetyCheck"] = lambda x: _CppBlockUtils.BtcUtils_getHash160_NoSafetyCheck
    __swig_getmethods__["getHash160"] = lambda x: _CppBlockUtils.BtcUtils_getHash160
    def getHash160_SWIG(self, *args): return _CppBlockUtils.BtcUtils_getHash160_SWIG(self, *args)
    def ripemd160_SWIG(self, *args): return _CppBlockUtils.BtcUtils_ripemd160_SWIG(self, *args)
    __swig_getmethods__["calculateMerkleRoot"] = lambda x: _CppBlockUtils.BtcUtils_calculateMerkleRoot
    __swig_getmethods__["calculateMerkleTree"] = lambda x: _CppBlockUtils.BtcUtils_calculateMerkleTree
    __swig_getmethods__["TxInCalcLength"] = lambda x: _CppBlockUtils.BtcUtils_TxInCalcLength
    __swig_getmethods__["TxOutCalcLength"] = lambda x: _CppBlockUtils.BtcUtils_TxOutCalcLength
    __swig_getmethods__["TxCalcLength"] = lambda x: _CppBlockUtils.BtcUtils_TxCalcLength
    __swig_getmethods__["getTxOutScriptType"] = lambda x: _CppBlockUtils.BtcUtils_getTxOutScriptType
    __swig_getmethods__["getTxInScriptType"] = lambda x: _CppBlockUtils.BtcUtils_getTxInScriptType
    __swig_getmethods__["getTxOutRecipientAddr"] = lambda x: _CppBlockUtils.BtcUtils_getTxOutRecipientAddr
    __swig_getmethods__["getTxInAddr"] = lambda x: _CppBlockUtils.BtcUtils_getTxInAddr
    __swig_getmethods__["convertDiffBitsToDouble"] = lambda x: _CppBlockUtils.BtcUtils_convertDiffBitsToDouble
    __swig_getmethods__["getOpCodeName"] = lambda x: _CppBlockUtils.BtcUtils_getOpCodeName
    __swig_getmethods__["convertScriptToOpStrings"] = lambda x: _CppBlockUtils.BtcUtils_convertScriptToOpStrings
    __swig_getmethods__["num2str"] = lambda x: _CppBlockUtils.BtcUtils_num2str
    __swig_getmethods__["pprintScript"] = lambda x: _CppBlockUtils.BtcUtils_pprintScript
    __swig_getmethods__["verifyProofOfWork"] = lambda x: _CppBlockUtils.BtcUtils_verifyProofOfWork
    __swig_destroy__ = _CppBlockUtils.delete_BtcUtils
    __del__ = lambda self : None;
BtcUtils_swigregister = _CppBlockUtils.BtcUtils_swigregister
BtcUtils_swigregister(BtcUtils)
cvar = _CppBlockUtils.cvar

def BtcUtils_readVarInt(*args):
  return _CppBlockUtils.BtcUtils_readVarInt(*args)
BtcUtils_readVarInt = _CppBlockUtils.BtcUtils_readVarInt

def BtcUtils_readVarIntLength(*args):
  return _CppBlockUtils.BtcUtils_readVarIntLength(*args)
BtcUtils_readVarIntLength = _CppBlockUtils.BtcUtils_readVarIntLength

def BtcUtils_calcVarIntSize(*args):
  return _CppBlockUtils.BtcUtils_calcVarIntSize(*args)
BtcUtils_calcVarIntSize = _CppBlockUtils.BtcUtils_calcVarIntSize

def BtcUtils_getHash256_NoSafetyCheck(*args):
  return _CppBlockUtils.BtcUtils_getHash256_NoSafetyCheck(*args)
BtcUtils_getHash256_NoSafetyCheck = _CppBlockUtils.BtcUtils_getHash256_NoSafetyCheck

def BtcUtils_getHash256(*args):
  return _CppBlockUtils.BtcUtils_getHash256(*args)
BtcUtils_getHash256 = _CppBlockUtils.BtcUtils_getHash256

def BtcUtils_getHash160_NoSafetyCheck(*args):
  return _CppBlockUtils.BtcUtils_getHash160_NoSafetyCheck(*args)
BtcUtils_getHash160_NoSafetyCheck = _CppBlockUtils.BtcUtils_getHash160_NoSafetyCheck

def BtcUtils_getHash160(*args):
  return _CppBlockUtils.BtcUtils_getHash160(*args)
BtcUtils_getHash160 = _CppBlockUtils.BtcUtils_getHash160

def BtcUtils_calculateMerkleRoot(*args):
  return _CppBlockUtils.BtcUtils_calculateMerkleRoot(*args)
BtcUtils_calculateMerkleRoot = _CppBlockUtils.BtcUtils_calculateMerkleRoot

def BtcUtils_calculateMerkleTree(*args):
  return _CppBlockUtils.BtcUtils_calculateMerkleTree(*args)
BtcUtils_calculateMerkleTree = _CppBlockUtils.BtcUtils_calculateMerkleTree

def BtcUtils_TxInCalcLength(*args):
  return _CppBlockUtils.BtcUtils_TxInCalcLength(*args)
BtcUtils_TxInCalcLength = _CppBlockUtils.BtcUtils_TxInCalcLength

def BtcUtils_TxOutCalcLength(*args):
  return _CppBlockUtils.BtcUtils_TxOutCalcLength(*args)
BtcUtils_TxOutCalcLength = _CppBlockUtils.BtcUtils_TxOutCalcLength

def BtcUtils_TxCalcLength(*args):
  return _CppBlockUtils.BtcUtils_TxCalcLength(*args)
BtcUtils_TxCalcLength = _CppBlockUtils.BtcUtils_TxCalcLength

def BtcUtils_getTxOutScriptType(*args):
  return _CppBlockUtils.BtcUtils_getTxOutScriptType(*args)
BtcUtils_getTxOutScriptType = _CppBlockUtils.BtcUtils_getTxOutScriptType

def BtcUtils_getTxInScriptType(*args):
  return _CppBlockUtils.BtcUtils_getTxInScriptType(*args)
BtcUtils_getTxInScriptType = _CppBlockUtils.BtcUtils_getTxInScriptType

def BtcUtils_getTxOutRecipientAddr(*args):
  return _CppBlockUtils.BtcUtils_getTxOutRecipientAddr(*args)
BtcUtils_getTxOutRecipientAddr = _CppBlockUtils.BtcUtils_getTxOutRecipientAddr

def BtcUtils_getTxInAddr(*args):
  return _CppBlockUtils.BtcUtils_getTxInAddr(*args)
BtcUtils_getTxInAddr = _CppBlockUtils.BtcUtils_getTxInAddr

def BtcUtils_convertDiffBitsToDouble(*args):
  return _CppBlockUtils.BtcUtils_convertDiffBitsToDouble(*args)
BtcUtils_convertDiffBitsToDouble = _CppBlockUtils.BtcUtils_convertDiffBitsToDouble

def BtcUtils_getOpCodeName(*args):
  return _CppBlockUtils.BtcUtils_getOpCodeName(*args)
BtcUtils_getOpCodeName = _CppBlockUtils.BtcUtils_getOpCodeName

def BtcUtils_convertScriptToOpStrings(*args):
  return _CppBlockUtils.BtcUtils_convertScriptToOpStrings(*args)
BtcUtils_convertScriptToOpStrings = _CppBlockUtils.BtcUtils_convertScriptToOpStrings

def BtcUtils_num2str(*args):
  return _CppBlockUtils.BtcUtils_num2str(*args)
BtcUtils_num2str = _CppBlockUtils.BtcUtils_num2str

def BtcUtils_pprintScript(*args):
  return _CppBlockUtils.BtcUtils_pprintScript(*args)
BtcUtils_pprintScript = _CppBlockUtils.BtcUtils_pprintScript

def BtcUtils_verifyProofOfWork(*args):
  return _CppBlockUtils.BtcUtils_verifyProofOfWork(*args)
BtcUtils_verifyProofOfWork = _CppBlockUtils.BtcUtils_verifyProofOfWork

DEFAULT_KDF_MAX_MEMORY = _CppBlockUtils.DEFAULT_KDF_MAX_MEMORY
class SecureBinaryData:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SecureBinaryData, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SecureBinaryData, name)
    __repr__ = _swig_repr
    __swig_destroy__ = _CppBlockUtils.delete_SecureBinaryData
    __del__ = lambda self : None;
    def getPtr(self, *args): return _CppBlockUtils.SecureBinaryData_getPtr(self, *args)
    def getSize(self): return _CppBlockUtils.SecureBinaryData_getSize(self)
    def copy(self): return _CppBlockUtils.SecureBinaryData_copy(self)
    def toHexStr(self, BE = False): return _CppBlockUtils.SecureBinaryData_toHexStr(self, BE)
    def toBinStr(self): return _CppBlockUtils.SecureBinaryData_toBinStr(self)
    def __init__(self, *args): 
        this = _CppBlockUtils.new_SecureBinaryData(*args)
        try: self.this.append(this)
        except: self.this = this
    def resize(self, *args): return _CppBlockUtils.SecureBinaryData_resize(self, *args)
    def reserve(self, *args): return _CppBlockUtils.SecureBinaryData_reserve(self, *args)
    def getRawCopy(self): return _CppBlockUtils.SecureBinaryData_getRawCopy(self)
    def getRawRef(self): return _CppBlockUtils.SecureBinaryData_getRawRef(self)
    def copySwapEndian(self, pos1 = 0, pos2 = 0): return _CppBlockUtils.SecureBinaryData_copySwapEndian(self, pos1, pos2)
    def append(self, *args): return _CppBlockUtils.SecureBinaryData_append(self, *args)
    def __add__(self, *args): return _CppBlockUtils.SecureBinaryData___add__(self, *args)
    def __eq__(self, *args): return _CppBlockUtils.SecureBinaryData___eq__(self, *args)
    def getHash256(self): return _CppBlockUtils.SecureBinaryData_getHash256(self)
    def getHash160(self): return _CppBlockUtils.SecureBinaryData_getHash160(self)
    def GenerateRandom(self, *args): return _CppBlockUtils.SecureBinaryData_GenerateRandom(self, *args)
    def lockData(self): return _CppBlockUtils.SecureBinaryData_lockData(self)
    def destroy(self): return _CppBlockUtils.SecureBinaryData_destroy(self)
SecureBinaryData_swigregister = _CppBlockUtils.SecureBinaryData_swigregister
SecureBinaryData_swigregister(SecureBinaryData)

class KdfRomix:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, KdfRomix, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, KdfRomix, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _CppBlockUtils.new_KdfRomix(*args)
        try: self.this.append(this)
        except: self.this = this
    def computeKdfParams(self, targetComputeSec = 0.25, maxMemReqtsBytes = 32*1024*1024): return _CppBlockUtils.KdfRomix_computeKdfParams(self, targetComputeSec, maxMemReqtsBytes)
    def usePrecomputedKdfParams(self, *args): return _CppBlockUtils.KdfRomix_usePrecomputedKdfParams(self, *args)
    def printKdfParams(self): return _CppBlockUtils.KdfRomix_printKdfParams(self)
    def DeriveKey_OneIter(self, *args): return _CppBlockUtils.KdfRomix_DeriveKey_OneIter(self, *args)
    def DeriveKey(self, *args): return _CppBlockUtils.KdfRomix_DeriveKey(self, *args)
    def getHashFunctionName(self): return _CppBlockUtils.KdfRomix_getHashFunctionName(self)
    def getMemoryReqtBytes(self): return _CppBlockUtils.KdfRomix_getMemoryReqtBytes(self)
    def getNumIterations(self): return _CppBlockUtils.KdfRomix_getNumIterations(self)
    def getSalt(self): return _CppBlockUtils.KdfRomix_getSalt(self)
    __swig_destroy__ = _CppBlockUtils.delete_KdfRomix
    __del__ = lambda self : None;
KdfRomix_swigregister = _CppBlockUtils.KdfRomix_swigregister
KdfRomix_swigregister(KdfRomix)

class CryptoAES:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, CryptoAES, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, CryptoAES, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _CppBlockUtils.new_CryptoAES()
        try: self.this.append(this)
        except: self.this = this
    def Encrypt(self, *args): return _CppBlockUtils.CryptoAES_Encrypt(self, *args)
    def Decrypt(self, *args): return _CppBlockUtils.CryptoAES_Decrypt(self, *args)
    __swig_destroy__ = _CppBlockUtils.delete_CryptoAES
    __del__ = lambda self : None;
CryptoAES_swigregister = _CppBlockUtils.CryptoAES_swigregister
CryptoAES_swigregister(CryptoAES)

class CryptoECDSA:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, CryptoECDSA, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, CryptoECDSA, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _CppBlockUtils.new_CryptoECDSA()
        try: self.this.append(this)
        except: self.this = this
    __swig_getmethods__["CreateNewPrivateKey"] = lambda x: _CppBlockUtils.CryptoECDSA_CreateNewPrivateKey
    __swig_getmethods__["ParsePrivateKey"] = lambda x: _CppBlockUtils.CryptoECDSA_ParsePrivateKey
    __swig_getmethods__["ParsePublicKey"] = lambda x: _CppBlockUtils.CryptoECDSA_ParsePublicKey
    __swig_getmethods__["SerializePrivateKey"] = lambda x: _CppBlockUtils.CryptoECDSA_SerializePrivateKey
    __swig_getmethods__["SerializePublicKey"] = lambda x: _CppBlockUtils.CryptoECDSA_SerializePublicKey
    def GenerateNewPrivateKey(self): return _CppBlockUtils.CryptoECDSA_GenerateNewPrivateKey(self)
    def ComputePublicKey(self, *args): return _CppBlockUtils.CryptoECDSA_ComputePublicKey(self, *args)
    def VerifyPublicKeyValid(self, *args): return _CppBlockUtils.CryptoECDSA_VerifyPublicKeyValid(self, *args)
    def CheckPubPrivKeyMatch(self, *args): return _CppBlockUtils.CryptoECDSA_CheckPubPrivKeyMatch(self, *args)
    def SignData(self, *args): return _CppBlockUtils.CryptoECDSA_SignData(self, *args)
    def VerifyData(self, *args): return _CppBlockUtils.CryptoECDSA_VerifyData(self, *args)
    def ComputeChainedPrivateKey(self, *args): return _CppBlockUtils.CryptoECDSA_ComputeChainedPrivateKey(self, *args)
    def ComputeChainedPublicKey(self, *args): return _CppBlockUtils.CryptoECDSA_ComputeChainedPublicKey(self, *args)
    __swig_destroy__ = _CppBlockUtils.delete_CryptoECDSA
    __del__ = lambda self : None;
CryptoECDSA_swigregister = _CppBlockUtils.CryptoECDSA_swigregister
CryptoECDSA_swigregister(CryptoECDSA)

def CryptoECDSA_CreateNewPrivateKey():
  return _CppBlockUtils.CryptoECDSA_CreateNewPrivateKey()
CryptoECDSA_CreateNewPrivateKey = _CppBlockUtils.CryptoECDSA_CreateNewPrivateKey

def CryptoECDSA_ParsePrivateKey(*args):
  return _CppBlockUtils.CryptoECDSA_ParsePrivateKey(*args)
CryptoECDSA_ParsePrivateKey = _CppBlockUtils.CryptoECDSA_ParsePrivateKey

def CryptoECDSA_ParsePublicKey(*args):
  return _CppBlockUtils.CryptoECDSA_ParsePublicKey(*args)
CryptoECDSA_ParsePublicKey = _CppBlockUtils.CryptoECDSA_ParsePublicKey

def CryptoECDSA_SerializePrivateKey(*args):
  return _CppBlockUtils.CryptoECDSA_SerializePrivateKey(*args)
CryptoECDSA_SerializePrivateKey = _CppBlockUtils.CryptoECDSA_SerializePrivateKey

def CryptoECDSA_SerializePublicKey(*args):
  return _CppBlockUtils.CryptoECDSA_SerializePublicKey(*args)
CryptoECDSA_SerializePublicKey = _CppBlockUtils.CryptoECDSA_SerializePublicKey



