// DO NOT MODIFY THIS FILE
// this file generated by createTestChain.py, modify that script instead
#ifndef BLKDATA_H
#define BLKDATA_H

namespace TestChain
{
const BinaryData addrA = BinaryData::CreateFromHex("62e907b15cbf27d5425399ebf6f0fb50ebb88f18");
const BinaryData scrAddrA = HASH160PREFIX + addrA;
const BinaryData addrB = BinaryData::CreateFromHex("ee26c56fc1d942be8d7a24b2a1001dd894693980");
const BinaryData scrAddrB = HASH160PREFIX + addrB;
const BinaryData privKeyAddrB = BinaryData::CreateFromHex("bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb");
const BinaryData addrC = BinaryData::CreateFromHex("cb2abde8bccacc32e893df3a054b9ef7f227a4ce");
const BinaryData scrAddrC = HASH160PREFIX + addrC;
const BinaryData privKeyAddrC = BinaryData::CreateFromHex("cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc");
const BinaryData addrD = BinaryData::CreateFromHex("c522664fb0e55cdc5c0cea73b4aad97ec8343232");
const BinaryData scrAddrD = HASH160PREFIX + addrD;
const BinaryData privKeyAddrD = BinaryData::CreateFromHex("dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd");
const BinaryData addrE = BinaryData::CreateFromHex("47b8ad0b1d6803260ce428d9e09e2cd99fd3b359");
const BinaryData scrAddrE = HASH160PREFIX + addrE;
const BinaryData privKeyAddrE = BinaryData::CreateFromHex("eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee");
const BinaryData addrF = BinaryData::CreateFromHex("d63b766cd342e6f0f7390dd454065e4bbea26b1b");
const BinaryData scrAddrF = HASH160PREFIX + addrF;
const BinaryData privKeyAddrF = BinaryData::CreateFromHex("efefefefefefefefefefefefefefefefefefefefefefefefefefefefefefefef");

const BinaryData blkHash0 = BinaryData::CreateFromHex("6fe28c0ab6f1b372c1a6a246ae63f74f931e8365e15a089c68d6190000000000");
const BinaryData blkHash1 = BinaryData::CreateFromHex("cf62cfe3a3686ec4f0c09d64a5fce8f1de37996d384a805b19fc316500000000");
const BinaryData blkHash2 = BinaryData::CreateFromHex("7b1561d24a566e7051268aadb1264c3b8865905bb17bd6c02195e26eeaadc15f");
const BinaryData blkHash3 = BinaryData::CreateFromHex("28953fc15c15f6d948c1383e19a74fd06f4a0c752accc79b624dba022abe0126");
const BinaryData blkHash4 = BinaryData::CreateFromHex("08ff45cd85c0ab679cc9bb6a318ca5486070e9197aa2ec3fa79aa71e00000000");
const BinaryData blkHash5 = BinaryData::CreateFromHex("71d47509174ac68b1642385e62f2eb6bb8335b8d1d4b3b5f95f18295223db2e9");
const BinaryData blkHash4A = BinaryData::CreateFromHex("177a3ca98318bb77c8414c321d290b396bb945c849781f26d7d42390f3fae9fe");
const BinaryData blkHash5A = BinaryData::CreateFromHex("5f089e11b0f9a106b6acd131f06aad6014b382614b5dbfeda7815849f0df6830");
}

#endif
