#! /bin/bash
set -e
if [ -d /usr/share/desktop-directories ] ; then
   xdg-desktop-menu  uninstall /usr/share/applications/armory.desktop
   xdg-desktop-menu  uninstall /usr/share/applications/armorytestnet.desktop
   xdg-desktop-menu  uninstall /usr/share/applications/armoryoffline.desktop
fi

xdg-icon-resource uninstall --size 64 armoryicon
xdg-icon-resource uninstall --size 64 armorytestneticon
xdg-icon-resource uninstall --size 64 armoryofflineicon

rm -f /usr/share/applications/armory.desktop
rm -f /usr/share/applications/armorytestnet.desktop
rm -f /usr/share/applications/armoryoffline.desktop

