#! /usr/bin/python

import os
import time
from subprocess import Popen, PIPE

def execAndWait(cli_str):
   print '\tEXEC:', cli_str
   process = Popen(cli_str, shell=True)
   while process.poll() == None:
      time.sleep(0.01)

def createDesktopFile(name, idstr, arglist, toDir=''):
   toPath = os.path.join(toDir, 'armory%s.desktop' % idstr) 
   deskfile = open(toPath, 'w')
   deskfile.write('[Desktop Entry]\n')
   deskfile.write('Type=Application\n')
   deskfile.write('Name=Armory')
   if name:
      deskfile.write(' (' + name + ')')
   deskfile.write('\n')
   deskfile.write('GenericName=Bitcoin Client\n')
   deskfile.write('Comment=Full-featured Bitcoin wallet management application\n')
   deskfile.write('Categories=Qt;Network;\n')
   deskfile.write('Exec=python /usr/share/armory/ArmoryQt.py')
   for a in arglist:
      deskfile.write(' --%s' % a)
   deskfile.write('\n')
   deskfile.write('Icon=armory%sicon\n' % idstr)
   deskfile.write('StartupNotify=false\n')
   deskfile.write('Terminal=false\n')
   deskfile.close()


createDesktopFile('','',[],'/usr/share/applications')

execAndWait('xdg-icon-resource install --novendor --context apps --size 64 /usr/share/armory/img/armory_icon_64x64.png armoryicon')
execAndWait('xdg-icon-resource install --novendor --context apps --size 64 /usr/share/armory/img/armory_icon_64x64.png armoryofflineicon')
execAndWait('xdg-icon-resource install --novendor --context apps --size 64 /usr/share/armory/img/armory_icon_green_64x64.png armorytestneticon')
execAndWait('xdg-desktop-menu  install --novendor /usr/share/applications/armory.desktop')
execAndWait('xdg-desktop-menu  install --novendor /usr/share/applications/armorytestnet.desktop')
execAndWait('xdg-desktop-menu  install --novendor /usr/share/applications/armoryoffline.desktop')


